### ISSUE TITLE
Something wrong with the network.py 

### ISSUE THREAD

**Issue by SinghSimranjeet** [Exaphis/HackQ-Trivia#101]
`Show active, connecting to socket at wss://ws-quiz.hype.space/ws/44773
Traceback (most recent call last):
  File ".\hq_main.py", line 62, in <module>
    asyncio.get_event_loop().run_until_complete(networking.websocket_handler(socket, headers))
  File "C:\Users\ssimr\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Users\ssimr\Documents\PythonPorj\GitHub Clones\HackQ-Trivia\networking.py", line 61, in websocket_handler
    raise RuntimeError("Connection settings invalid")
RuntimeError: Connection settings invalid`

I know this is too much to ask but can someone just tells me how I can sniff and find the bearer token and user ID. I'm using Wireshark. Like someone tells me what I'm looking for in the traffic what kind of protocol, and how I can decrypt it if needed.

Sorry that I'm lacking the knowledge. The answer to this won't just help me but someone who also has the same problem.

Thank you

**Comment by CrazyReturns** [comment]
BEARER:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1OTQ0MTI2LCJ1c2VybmFtZSI6IkFsZXhhbmRlclNpZmZpIiwiYXZhdGFyVXJsIjoiczM6Ly9oeXBlc3BhY2UtcXVpei9hL2JiLzE1OTQ0MTI2LUhpV0M3ci5qcGciLCJ0b2tlbiI6IlVYcW4wYyIsInJvbGVzIjpbXSwiY2xpZW50IjoiIiwiZ3Vlc3RJZCI6bnVsbCwidiI6MSwiaWF0IjoxNTIzOTY5NjA1LCJleHAiOjE1MzE3NDU2MDUsImlzcyI6Imh5cGVxdWl6LzEifQ.Nm0p2g7_DhsJoWmB3tSbLGpELe4zkchxRrrmS7my_Qc

ID(US):15944126


Unless you have an iPhone, you're going to have a difficult time. There is a thread that discusses this here: https://github.com/Exaphis/HackQ-Trivia/issues/76

**Comment by SinghSimranjeet** [comment]
@CrazyReturns Thank you, let's hope HQ doesn't ban this userID. Going to use Charles to find my bearer and userID.
