### ISSUE TITLE
How to get bearer token and user ID?

### ISSUE THREAD

**Issue by elesgood** [Exaphis/HackQ-Trivia#103]
Hello guys I can't find my Bearer token and user ID on charles proxy. I've downloaded the certifiacte on an iOS device, but when I connect it, it just freezes at 'sending request body'  could anyone please help me how to get my bearer token and user id? Thanks.

**Comment by iceeb** [comment]
Same, need help with this

**Comment by jdleo** [comment]
@iceeb @sam-malanchuk come on. burp suite. it's the easiest thing ever.

**Comment by botinger** [comment]
Easy Way with Android.
packet capture -> Link: https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=en

Install then own SSL certifikat and then you can record the stream for one APP or for all.

Packet Capture work as "man in the middle".

![screenshot-1528050726703 - kopie](https://user-images.githubusercontent.com/39875227/40889950-f8b83658-676e-11e8-871b-2e05d0cece06.jpg)
![screenshot-1528050739685 - kopie](https://user-images.githubusercontent.com/39875227/40889951-f8d3b266-676e-11e8-88f2-88fee14f316e.jpg)

**Comment by sam-malanchuk** [comment]
@botinger doesn’t work for me on a Samsung Galaxy S7. As soon as I start the Packet Capure and go to HQ. The app doesn’t respond. I think they see the certificate and block out the connection. Upon disabling the capture, HQ returns back to normal

**Comment by Exaphis** [comment]
@sam-malanchuk I encountered the same problem. You either have to decompile the app to allow the certificate (haven't done it, but I've heard its possible) or use an Android phone before Android Nougat or an iPhone to get the bearer token.

**Comment by sam-malanchuk** [comment]
I have an iPhone, haven’t found a way to find the bearer token though. Any suggestions?

**Comment by Exaphis** [comment]
A friend of mine was able to get his bearer token with Charles. This was around February, so HQ might have changed something since then.

**Comment by SinghSimranjeet** [comment]
NVM I tried using a different android phone I had relying on which had the Android version 6.0. Using the SSL Packet Sniffer app I was able to find the Bearer Token. It's pretty easy, all you need to know that you need Android version of 6 or lower in order to sniff the bearer token.

**Comment by bacondude3** [comment]
Hey guys I don't know any easier way to obtain your Bearer Token on iPhone aside from sniffing traffic, but as for android I came across this - http://hqmakeitrain.tk/ -  Haven't tested it but I've been told it works. It would make the process on android a whole lot simpler.

**Comment by Exaphis** [comment]
An emulator would work just fine.
