### ISSUE TITLE
Server Timeout error

### ISSUE THREAD

**Issue by VaporrPlays** [Exaphis/HackQ-Trivia#107]
> Server timeout/error to https://www.google.com/

Every time the bot detects a question, each method has a server timeout error, providing no results.

**Comment by Exaphis** [comment]
Could you post your log file here? It may be because you don't have a fast enough internet connection.

**Comment by VaporrPlays** [comment]
Hi there!
Reading other issues, Ive tried to increase timeout times but it hasn't changed; the search time remains the same. I have re-downloaded the bot, in need to retry it again.
Here's the log:

> INFO:root:{'active': True, 'atCapacity': False, 'showId': 5093, 'showType': 'hq-uk', 'startTime': '2018-05-29T14:00:00.000Z', 'nextShowTime': None, 'nextShowPrize': None, 'upcoming': [{'time': '2018-05-29T20:00:00.000Z', 'prize': '£1,000'}], 'prize': 1000, 'broadcast': {'broadcastId': 45042, 'userId': 38752, 'title': 'Wirecast stream', 'status': 1, 'state': 'live', 'channelId': 100, 'created': '2018-05-29T13:55:11.000Z', 'started': '2018-05-29T13:55:11.000Z', 'ended': None, 'permalink': 'https://hy.pe/b/ahW', 'thumbnailData': None, 'tags': [], 'socketUrl': 'https://ws-quiz.hype.space/ws/45042', 'streams': {'source': 'rtsp://edge-hq-uk.hype.space:1935/live/wirecast_high', 'passthrough': 'rtsp://edge-hq-uk.hype.space:1935/live/wirecast_high', 'high': 'rtsp://edge-hq-uk.hype.space:1935/live/wirecast_high', 'medium': 'rtsp://edge-hq-uk.hype.space:1935/live/wirecast_medium', 'low': 'rtsp://edge-hq-uk.hype.space:1935/live/wirecast_low'}, 'streamUrl': 'rtsp://edge-hq-uk.hype.space:1935/live/wirecast_high', 'streamKey': 'wirecast', 'relativeTimestamp': 7543, 'links': {'self': '/broadcasts/45042', 'transcript': '/broadcasts/45042/transcript', 'viewers': '/broadcasts/45042/viewers'}}, 'gameKey': 'hq-uk:9', 'vertical': 'general', 'broadcastFull': False}
INFO:root:b"{'type': 'interaction', 'ts': '2018-05-29T14:07:26.674Z', 'itemId': 'chat', 'userId': 17020248, 'metadata': {'avatarUrl': 'https://d2xu1hdomh3nrx.cloudfront.net/72x72/a/97/17020248-4ytADJ.jpg', 'interaction': 'chat', 'message': 'pluto isnt a planet', 'userId': 17020248, 'username': 'dazwilkinson'}, 'sent': '2018-05-29T14:07:26.730Z'}"
INFO:root:b"{'type': 'gameStatus', 'ts': '2018-05-29T14:07:26.846Z', 'inTheGame': True, 'showId': 5093, 'prize': '\xc2\xa31,000', 'extraLives': 1, 'extraLivesRemaining': 1, 'cardPlaysRemaining': 0, 'questionId': 42241, 'questionNumber': 6, 'questionCount': 12, 'currentState': {'type': 'questionFinished', 'questionId': '42241'}, 'sent': '2018-05-29T14:07:26.846Z'}"
INFO:root:{'type': 'gameStatus', 'ts': '2018-05-29T14:07:26.846Z', 'inTheGame': True, 'showId': 5093, 'prize': '£1,000', 'extraLives': 1, 'extraLivesRemaining': 1, 'cardPlaysRemaining': 0, 'questionId': 42241, 'questionNumber': 6, 'questionCount': 12, 'currentState': {'type': 'questionFinished', 'questionId': '42241'}, 'sent': '2018-05-29T14:07:26.846Z'}
INFO:root:b"{'type': 'broadcastStats', 'ts': '2018-05-29T14:07:26.845Z', 'statusMessage': '', 'userId': 11543313, 'viewerCounts': {'connected': 62611, 'playing': 20934, 'watching': 40085}, 'sent': '2018-05-29T14:07:26.846Z'}"
INFO:root:{'type': 'broadcastStats', 'ts': '2018-05-29T14:07:26.845Z', 'statusMessage': '', 'userId': 11543313, 'viewerCounts': {'connected': 62611, 'playing': 20934, 'watching': 40085}, 'sent': '2018-05-29T14:07:26.846Z'}
INFO:root:b"{'type': 'interaction', 'ts': '2018-05-29T14:07:26.867Z', 'itemId': 'chat', 'userId': 16191152, 'metadata': {'userId': 16191152, 'message': 'Shazza that\xe2\x80\x99s not a planet', 'avatarUrl': 'https://d2xu1hdomh3nrx.cloudfront.net/72x72/a/a9/16191152-5SNaVj.jpg', 'interaction': 'chat', 'username': 'Cheytdw'}, 'sent': '2018-05-29T14:07:26.876Z'}"
INFO:root:b"{'type': 'interaction', 'ts': '2018-05-29T14:07:27.119Z', 'itemId': 'chat', 'userId': 19595704, 'metadata': {'avatarUrl': 'https://d2xu1hdomh3nrx.cloudfront.net/72x72/default_avatars/Untitled-1_0002_purple.png', 'interaction': 'chat', 'message': 'plutos not even a planet', 'userId': 19595704, 'username': 'JamesShaw96'}, 'sent': '2018-05-29T14:07:27.111Z'}"
INFO:root:b'{\'type\': \'question\', \'ts\': \'2018-05-29T14:07:27.130Z\', \'totalTimeMs\': 10000, \'timeLeftMs\': 10000, \'questionId\': 42242, \'question\': "Which character has NOT been enrolled in Mrs. Puff\'s Boating School in \xe2\x80\x9cSpongebob\xe2\x80\x9d?", \'category\': \'TV\', \'answers\': [{\'answerId\': 128866, \'text\': \'Mr. Krabs\'}, {\'answerId\': 128867, \'text\': \'Sandy\'}, {\'answerId\': 128868, \'text\': \'Plankton\'}], \'questionNumber\': 7, \'questionCount\': 12, \'askTime\': \'2018-05-29T14:07:27.130Z\', \'c\': 1, \'sent\': \'2018-05-29T14:07:27.152Z\'}'
INFO:root:{'type': 'question', 'ts': '2018-05-29T14:07:27.130Z', 'totalTimeMs': 10000, 'timeLeftMs': 10000, 'questionId': 42242, 'question': "Which character has NOT been enrolled in Mrs. Puff's Boating School in “Spongebob”?", 'category': 'TV', 'answers': [{'answerId': 128866, 'text': 'Mr. Krabs'}, {'answerId': 128867, 'text': 'Sandy'}, {'answerId': 128868, 'text': 'Plankton'}], 'questionNumber': 7, 'questionCount': 12, 'askTime': '2018-05-29T14:07:27.130Z', 'c': 1, 'sent': '2018-05-29T14:07:27.152Z'}
ERROR:root:Server timeout/error to https://www.google.com/search?q=character+enrolled+mrs+puff+boating+school+spongebob&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
Traceback (most recent call last):
  File "C:\Users\VaporrPlays\AppData\Local\Programs\Python\Python36\lib\site-packages\aiohttp\connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "C:\Users\VaporrPlays\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 777, in create_connection
    raise exceptions[0]
  File "C:\Users\VaporrPlays\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 764, in create_connection
    yield from self.sock_connect(sock, address)
  File "C:\Users\VaporrPlays\AppData\Local\Programs\Python\Python36\lib\asyncio\selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "C:\Users\VaporrPlays\AppData\Local\Programs\Python\Python36\lib\asyncio\selector_events.py", line 480, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
OSError: [Errno 10051] Connect call failed ('2a00:1450:4009:80c::2004', 443)

**Comment by ethanmarcus18** [comment]
Same here, did you find a fix?

**Comment by dabsihsay** [comment]
@Exaphis I'm having this issue aswell. Let us know how to fix it please!

**Comment by Exaphis** [comment]
I have a few questions for those having this problem. Does this happen every single time HQ is on? Has this happened consistently since your installation? Does this happen on another network/another computer?

**Comment by dabsihsay** [comment]
@Exaphis Do you have discord so we can talk about this? Sorry to invade

**Comment by dabsihsay** [comment]
@Exaphis This happens every time HQ has been on. Ever since I installed it has always said Server Timeout. Never tried on another device.

**Comment by Exaphis** [comment]
@dabsihsay Could you try using this on another computer?

**Comment by U-r-Unknown** [comment]
Exaphis bro what happened to loco project
