### ISSUE TITLE
Make an app for Loco and Brainbaazi

### ISSUE THREAD

**Issue by sensuraj** [Exaphis/HackQ-Trivia#108]
Hlo sir,  I really appreciate your bot. But we need a bot for loco and Brainbaazi which should be 99% accurate.
We are even going to pay u whatever amount you want. So plzz contact me at sensuraj060@gmail.com

**Comment by tdaddy** [comment]
lmao

**Comment by sensuraj** [comment]
What's imao by the way?

**Comment by sensuraj** [comment]
ROFL
