### ISSUE TITLE
I think I did everything right now how do I actaully

### ISSUE THREAD

**Issue by healur** [Exaphis/HackQ-Trivia#11]
how do I run it or what do I click

**Comment by Exaphis** [comment]
You run hq_main.py in your IDE of choice or in the command line.

**Comment by healur** [comment]
so I just put the code into python the idle folder

**Comment by Exaphis** [comment]
You can just open hq_main with IDLE.

**Comment by healur** [comment]
thanks. just one more thing how do I get the bearer token do I use Charles proxy or is there an easier way

**Comment by Exaphis** [comment]
https://github.com/gjacobs314/HQTrivia has two example bearer tokens/user IDs for you to use.

**Comment by Exaphis** [comment]
You have to run the code. If the show's not on, it should say so.

**Comment by Exaphis** [comment]
Please post a screenshot of the error. Alternatively, you could run ```python3 hq_main```in cmd/terminal with your working directory being in the HackQ-Trivia folder.

**Comment by healur** [comment]
<img width="733" alt="screen shot 2018-03-10 at 2 53 31 pm" src="https://user-images.githubusercontent.com/37125581/37246644-e287252c-2472-11e8-9d79-976a8fac3539.png">

**Comment by healur** [comment]
do you know what I did wrong?

**Comment by Exaphis** [comment]
Try right clicking. Under open with, click IDLE. The code should pop up in a new window instead of the shell.

**Comment by healur** [comment]
<img width="671" alt="screen shot 2018-03-10 at 4 32 05 pm" src="https://user-images.githubusercontent.com/37125581/37247460-af0c9a3e-2480-11e8-94e0-9ed75fc154b0.png">

**Comment by healur** [comment]
I did that but how do I run it now

**Comment by Exaphis** [comment]
You can press fn+F5 or go to Run->Run Module.

**Comment by healur** [comment]
<img width="726" alt="screen shot 2018-03-10 at 4 37 24 pm" src="https://user-images.githubusercontent.com/37125581/37247494-5fc1dd26-2481-11e8-90de-f037b16a2472.png">
this happened

**Comment by Exaphis** [comment]
Now, you need to install the dependencies for the program. In terminal, run: 
```
pip install bs4
pip install nltk
pip install aiohttp
pip install unidecode
```

After you install those, you need to run these 3 lines of code in the IDLE shell:
```
import nltk
nltk.download("stopwords")
nltk.download("averaged_perceptron_tagger")
```

You then need to enter your bearer token/user ID.

**Comment by healur** [comment]
terminal says pip command not found

**Comment by Exaphis** [comment]
Try using pip3 instead of pip. If that doesn't work, try running  ``` sudo easy_install pip ``` before running those 3 commands again.

**Comment by healur** [comment]
all of them installed with pip3 except ntlk one

**Comment by Exaphis** [comment]
What does it say when you install nltk?

**Comment by healur** [comment]
it worked I think I just typed it wrong the first time

**Comment by Exaphis** [comment]
Alright. Let me know if you have any more problems.

**Comment by healur** [comment]
ok I just did those steps now do I rerun the script

**Comment by Exaphis** [comment]
Yes.

**Comment by healur** [comment]
ok thanks

**Comment by healur** [comment]
ok thanks I think it works it says show not on

**Comment by Exaphis** [comment]
Yep, that's what it's supposed to say.

**Comment by healur** [comment]
ok thank you so much
