### ISSUE TITLE
broadcast error- hq changed the header required for getting broadcast url

### ISSUE THREAD

**Issue by mashukmashum** [Exaphis/HackQ-Trivia#110]
from past two days this script is not working. when I sniffed packet using packet capture, i found that hq has added ccountry parameter to headers and that could be the reason for the script to be not working. please add a fix to this

**Comment by AyJavasProcessing** [comment]
Same! Its not working for me either now. A fix will be highly appreciated!

**Comment by Exaphis** [comment]
I have had no problem connecting to today's game or yesterday's game.

**Comment by mashukmashum** [comment]
ok i will try today, may be that the token or userid I am using got banned

**Comment by AyJavasProcessing** [comment]
@mashukmashum let me know!!

**Comment by Exaphis** [comment]
No response for 6 days, assuming solved. Check #113 if you are still having problems, your bearer token may have expired.
