### ISSUE TITLE
Getting 0 results

### ISSUE THREAD

**Issue by dxrkforce** [Exaphis/HackQ-Trivia#112]
Recently I have realized that I am not getting any results (no keywords or noun results). I think it might have something to do with the google search API, but don't know how to make it work again. Any tips or any solutions anyone has would be great!
From command prompt- https://darktv.xyz/i/VKCHP
[No results.txt](https://github.com/Exaphis/HackQ-Trivia/files/2046198/No.results.txt)

**Comment by Exaphis** [comment]
Could you post your log file here? It may be because you don't have a fast enough internet connection.

**Comment by darkRL** [comment]
Ive been using the bot for 1-2 months now flawlessly, updating the files whenever necessary and even changing the bearer and ID. I'd like to give this information, but I don't see a log file

**Comment by Exaphis** [comment]
The log file would be the ```data.log``` inside your HackQ-Trivia folder.

**Comment by darkRL** [comment]
[data.log](https://github.com/Exaphis/HackQ-Trivia/files/2050538/data.log)

**Comment by Exaphis** [comment]
@mustafahafidi Could you post your log file as well? Does this happen every single time you run the program? Has this happened consistently since your installation? Does this happen on another network/another computer?

**Comment by mustafahafidi** [comment]
This is a problem related with the google search, I mocked the wss server and I can see that `
    search_results = await search.search_google("+".join(question_keywords), 5)` returns an empty list

[datamocked.log](https://github.com/Exaphis/HackQ-Trivia/files/2100643/datamocked.log)
[dataoriginal.log](https://github.com/Exaphis/HackQ-Trivia/files/2100644/dataoriginal.log)

**Comment by mustafahafidi** [comment]
Update: It's related to the \x escape sequence (which explains why we get inappropriate results from the google search), cleaning them correctly solves the issue. @Exaphis

**Comment by darkRL** [comment]
@mustafahafidi could you send me the file with the fix?

**Comment by mustafahafidi** [comment]
In file `networking.py` look for the line `message = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", message)` and add right after it:
            `message = re.sub(r"\\x..", "", str(message.encode("utf-8"))[2:-1])
            message = re.sub(r"\\", "", str(message.encode("utf-8"))[2:-1])` not clean but works, let me know

**Comment by Jasperaj** [comment]
> In file `networking.py` look for the line `message = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", message)` and add right after it:
> `message = re.sub(r"\\x..", "", str(message.encode("utf-8"))[2:-1])`
> `message = re.sub(r"\\", "", str(message.encode("utf-8"))[2:-1])`
> not clean but it works, let me know

@mustafahafidi  Adding also gave 0 results. Any other option?
