### ISSUE TITLE
Connection Settings Invalid error

### ISSUE THREAD

**Issue by AyJavasProcessing** [Exaphis/HackQ-Trivia#113]
Did I get this error because my bearer token and id are banned? The script used to run perfectly fine. Not too familiar with programming. What can I do?

Thanks in advance and great work!
![capture1](https://user-images.githubusercontent.com/39684042/40629769-6aa7cb4e-629b-11e8-9ee7-f3b87409eea8.PNG)

**Comment by Exaphis** [comment]
Possibly, but I haven't had a bearer token banned before. You can enter your bearer token on https://jwt.io/, hover over the ```exp``` in the payload section, and see if it has expired. If it has, then you need to get a new bearer token by sniffing your traffic.

**Comment by AyJavasProcessing** [comment]
Thanks!
