### ISSUE TITLE
How do you find user id?

### ISSUE THREAD

**Issue by larry7101** [Exaphis/HackQ-Trivia#114]
I found the bearer token but idk how to get the user id. Can anyone help me?

**Comment by Exaphis** [comment]
There is actually no need for the user ID anymore, so I have removed it in commit https://github.com/Exaphis/HackQ-Trivia/commit/d477630a96177856c2cf2586120ec5d91de7f0e6. It should have worked even without the user ID before.

**Comment by ritupratik** [comment]
> There is actually no need for the user ID anymore, so I have removed the option to enter it in commit [d477630](https://github.com/Exaphis/HackQ-Trivia/commit/d477630a96177856c2cf2586120ec5d91de7f0e6). It should have worked even without the user ID before.

sir i need help
