### ISSUE TITLE
'git' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by sidknows** [Exaphis/HackQ-Trivia#115]
C:\Users\vicky\Documents\hq>git clone https://github.com/Exaphis/HackQ-Trivia.gi t 'git' is not recognized as an internal or external command, operable program or batch file. 
while python is installed 
![not](https://user-images.githubusercontent.com/39224460/40680922-471c0946-63a5-11e8-8586-0f9eb97f6520.JPG)
![bot](https://user-images.githubusercontent.com/39224460/40680997-83426596-63a5-11e8-9af9-1b6d5fbcd5e4.JPG)

**Comment by Exaphis** [comment]
Click the green ```Clone or Download``` button, download the repository as a zip, unzip it, and follow the instructions from there. Instead of ```cd HackQ-Trivia```, it will be ```cd Downloads\HackQ-Trivia-master```.
