### ISSUE TITLE
Is there a way to connect using vpn or proxy?

### ISSUE THREAD

**Issue by nuriaymarco03** [Exaphis/HackQ-Trivia#116]
Congrats for the job! It s works Fine.
Using it from cmd in windows. I dont want to connect the bot from the same ip that im playing (i cant play with 3g/4g)Is theres a way to tell the the cmd to connect from a vpn/proxy or modify py code to do that? 
Idont wanna conect all the computer to vpn; only the bot. Its this posible?

**Comment by AyJavasProcessing** [comment]
Yeah, was wondering if its safe to play without one.
