### ISSUE TITLE
How only display answers (and nothing else)// ITs  posible to run it under android?

### ISSUE THREAD

**Issue by nuriaymarco03** [Exaphis/HackQ-Trivia#117]
Hi! I am testing a lot of bots and for now is far the best i've used. The only thing that is not comfortable to my is that the way that the programs display the results: It starts with method 1; display in green the result it gives but then runs method 3 and there a lot of text before the new result (pages founded, pages not founded, etc)

So when i try to compare the results of the different method i tried to scroll up and down and meanwhile the 10 seconds pass away.  How could i modify the code to show my only the Method using, the points that get each answer with this method and the green answer that is the best in that method? I understand what is searching every method so for my the best way to use it is displaying only this few things.
Sorry if its a very simple cuestiong i had read the code but im scared to touch anything incorrect and break a code that is very is like a clockwork.

On the other hand: had anyone tried to run it on android? It would be cool to have it on one cell and use it anywhere without needing a pc. Had anybody a idea of how to do it?

**Comment by fuomag9** [comment]
You could rent a cheap vps and run on it and read the output via ssh for example. I don't know if the python3 libraries used here are full supported and work correctly in a python env on android, but you might give it a try using termux for example.

**Comment by vocabexpresshaxer** [comment]
Use pydroid3 on Android, that works great
