### ISSUE TITLE
bearer token help

### ISSUE THREAD

**Issue by bburghall** [Exaphis/HackQ-Trivia#119]
I had done this in the past but currently have issues. Could anybody share a US bearer token or a detailed guide? it's all I need.

**Comment by ethanmarcus18** [comment]
Download Charles proxy on your laptop and get an ssl certificate downloaded on to your device and verify it. Then hop onto the HQ app and intercept the packets going from your phone to HQ. The bearer token and userID should be somewhere in there.

**Comment by bburghall** [comment]
Thank you. I had actually done it successfully before but on my last attempt I struggled to find it in my sniffed traffic. Could anybody share one? I have a uk one but it's not ideal

**Comment by bzhu9** [comment]
here is a US one:
bearer=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjkxOTM4NzYsInVzZXJuYW1lIjoicG90YXRvMjUyIiwiYXZhdGFyVXJsIjoiczM6Ly9oeXBlc3BhY2UtcXVpei9kZWZhdWx0X2F2YXRhcnMvVW50aXRsZWQtMV8wMDAzX3JlZC5wbmciLCJ0b2tlbiI6Ik02VURIaCIsInJvbGVzIjpbXSwiY2xpZW50IjoiIiwiZ3Vlc3RJZCI6bnVsbCwidiI6MSwiaWF0IjoxNTIzNDc1MjUyLCJleHAiOjE1MzEyNTEyNTIsImlzcyI6Imh5cGVxdWl6LzEifQ.xAfoFWg_LQy8xSL_meaOHm5YjWFLdh8yZusPVYKX_S4
