### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by sparklything** [Exaphis/HackQ-Trivia#12]
I think I did everything right, but i'm getting a key error when I try to run it.
What happens is:

<img width="572" alt="screen shot 2018-03-07 at 8 55 47 pm" src="https://user-images.githubusercontent.com/37203304/37191540-52a362d0-232e-11e8-8464-fdb6ec9a80dd.png">

then it just stops. Any idea as to what could be wrong?

**Comment by Exaphis** [comment]
Could you send me the data in your log file?

**Comment by Exaphis** [comment]
You probably have entered an incorrect bearer token in the conn_settings.txt file.

**Comment by sparklything** [comment]
Thanks, there was a space before my user ID which was messing it up. Thanks for the help!
