### ISSUE TITLE
AFter one week of running properly i get this error     logging.fatal(f"Settings read error: {settings}")                                                    ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nuriaymarco03** [Exaphis/HackQ-Trivia#124]
I used the bot correctly for one week but then i get this error:
    logging.fatal(f"Settings read error: {settings}")
                                                   ^
SyntaxError: invalid syntax

Could it be some problem with the bearer token? That they banned me or anything?
I checked jwt.io and after my used name and i get this, but its appears to be ok...
"avatarUrl": "s3://hypespace-quiz/default_avatars/Untitled-1_0001_blue.png",
  "token": "vZ8tzD",
  "roles": [],
  "client": "",
  "guestId": null,
  "v": 1,
  "iat": 1527112749,
  "exp": 1534888749,
  "iss": "hypequiz/1"

Also i can enter to HQ ( i didnt probe it during a game, but i can see the next game, etc)

Could it be some problem with Python 27? I the last days i ve installed also python 27 and libraries but i dont understand if it could be related to the problema, because the error msg doesnt says anything that give me a clue).

**Comment by Exaphis** [comment]
Could you try downloading the repository again and trying that? The file might have been changed somehow.

**Comment by Exaphis** [comment]
Furthermore, make sure you are running Python 3.6 instead of 2.7.

**Comment by nuriaymarco03** [comment]
You are right. It was a conflict with python versions; i was sure that 3.6 was the predeterminated versions but its not.
COuld it be that i introduced pythons 27 path  pythons 36 path in the environment variable?

**Comment by Exaphis** [comment]
That's probably why.
