### ISSUE TITLE
How do i get my bearer token?

### ISSUE THREAD

**Issue by cillakiez** [Exaphis/HackQ-Trivia#127]
I use an iPhone and it seems the lot of you use Android, no one has provided a solution for iOS. I'm not sure how to get a bearer token, i installed Charles Proxy but have not the slightest idea on how to use it. Does this involve on having a rooted device as well? If so is it possible to get a bearer token on an unrooted iPhone? This seems to be the only issue i'm having.

**Comment by shaun1x** [comment]
You dont need to have root access to be able to use Charles proxy on the iphone. You just need to know the IP address of the machine which is running it.

When Charles is running you can go to your Wifi settings on your phone and set up a manual proxy. Enter the machines IP address and the port is usually 8888.

You should be set to go from there

**Comment by cillakiez** [comment]
I don’t see a bearer token anywhere in Charles proxy, neither a user ID.

**Comment by shaun1x** [comment]
You don't need a UserID anymore, just the bearer token.

Can you see the traffic coming through Charles?

**Comment by iceeb** [comment]
@shaun1x I have used charles and cannot find bearer token, anyway to reach u faster (discord, whatsapp, telegram)?

**Comment by bzhu9** [comment]
just use this one
bearer=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjkxOTM4NzYsInVzZXJuYW1lIjoicG90YXRvMjUyIiwiYXZhdGFyVXJsIjoiczM6Ly9oeXBlc3BhY2UtcXVpei9kZWZhdWx0X2F2YXRhcnMvVW50aXRsZWQtMV8wMDAzX3JlZC5wbmciLCJ0b2tlbiI6Ik02VURIaCIsInJvbGVzIjpbXSwiY2xpZW50IjoiIiwiZ3Vlc3RJZCI6bnVsbCwidiI6MSwiaWF0IjoxNTIzNDc1MjUyLCJleHAiOjE1MzEyNTEyNTIsImlzcyI6Imh5cGVxdWl6LzEifQ.xAfoFWg_LQy8xSL_meaOHm5YjWFLdh8yZusPVYKX_S4
