### ISSUE TITLE
Getting 0 results on UK but works fine for US

### ISSUE THREAD

**Issue by DWD420** [Exaphis/HackQ-Trivia#129]
Hi, works great for US but for UK i get 0 error due to google server timeout. 

Any help would be appreciated.

Question detected.
Question 11 out of 12
[36mIn which of these TV programmes has Lin-Manuel Miranda NOT appeared?
['Curb Your Enthusiasm', 'Arrested Development', 'How I Met Your Mother'][0m

Searching
['Curb Your Enthusiasm', 'Arrested Development', 'How I Met Your Mother']
['tv', 'programmes', 'lin', 'manuel', 'miranda', 'appeared']
Server timeout/error to https://www.google.com/search?q=tv+programmes+lin+manuel+miranda+appeared&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
[]
Running method 1
{'curb your enthusiasm': 0, 'arrested development': 0, 'how i met your mother': 0}
Running method 2
{'Curb Your Enthusiasm': {'curb': 0, 'enthusiasm': 0}, 'Arrested Development': {'arrested': 0, 'development': 0}, 'How I Met Your Mother': {'met': 0, 'mother': 0}}
[('In', 'IN'), ('which', 'WDT'), ('of', 'IN'), ('these', 'DT'), ('TV', 'NN'), ('programmes', 'NNS'), ('has', 'VBZ'), ('Lin-Manuel', 'JJ'), ('Miranda', 'NNP'), ('NOT', 'NNP'), ('appeared', 'VBD'), ('?', '.')]
Question nouns: {'manuel miranda', 'miranda not'}
Running method 3
Server timeout/error to https://www.google.com/search?q=Curb Your Enthusiasm&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
Server timeout/error to https://www.google.com/search?q=Arrested Development&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
Server timeout/error to https://www.google.com/search?q=How I Met Your Mother&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
Search processed
URLs fetched

Curb Your Enthusiasm: {}
Arrested Development: {}
How I Met Your Mother: {}

Keyword scores: {'Curb Your Enthusiasm': 0, 'Arrested Development': 0, 'How I Met Your Mother': 0}
Noun scores: {'Curb Your Enthusiasm': 0, 'Arrested Development': 0, 'How I Met Your Mother': 0}
[32m[0m
Search took 0.299574613571167 seconds

**Comment by shaun1x** [comment]
I just ran this in the UK and seemed to work fine. 

Were you behind a VPN?

**Comment by DWD420** [comment]
Hi @shaun1x 

Was running with no vpn, i was using a UK bearer token that was shared in the comments, as the questions were coming up i was assuming that this was not the issue. 

Aside from that i do not know what it could be.

**Comment by shaun1x** [comment]
Maybe the shared token was the problem. Send me the token and I can check it tonight for you. 

⁣Sent from BlueMail ​

**Comment by DWD420** [comment]
appreciate the help


eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2ODkwMTk3LCJ1c2VybmFtZSI6IklMb3ZlU3BvbmdlcyIsImF2YXRhclVybCI6InMzOi8vaHlwZXNwYWNlLXF1aXovYS9hMy8xNjg5MDE5Ny1pd1pMcmcuanBnIiwidG9rZW4iOiJnYTJnOGUiLCJyb2xlcyI6W10sImNsaWVudCI6IiIsImd1ZXN0SWQiOm51bGwsInYiOjEsImlhdCI6MTUyMzkwNzc5NSwiZXhwIjoxNTMxNjgzNzk1LCJpc3MiOiJoeXBlcXVpei8xIn0.yja1F-Y8VdjPO_GjXTXSpWweL3NQQPNnTSt_Zqaeh88

**Comment by shaun1x** [comment]
Token seems fine and still valid until next month. I can run it on tomorrow game during the day, but the only other thing I think of is that it was just a glitch and maybe will work. 

Maybe you need to get a new UK token.

**Comment by blazeresells** [comment]
@shaun1x could you come in a voice chat in discord and help me set this up?

**Comment by DWD420** [comment]
Thanks @shaun1x 

Do I need to change something other than conn_setting.txt as this still comes up as google server error

**Comment by shaun1x** [comment]
@DWD420 - Sorry, A google issue wont have anything to do with your Bearer token as that token is to fetch the questions only. Its possible that google have flagged your IP and asking for a captcha request, right now there isn't much you can do about that other than using a VPN ( I think, not had this issue before )

@blazeresells Feel free to add me on Discord - shaunix#9052 - I can't guaranteed when I would be on, but if we are on at the same time at some point, I can probably help out.

**Comment by Exaphis** [comment]
Try the new version, let me know if you have any problems.
