### ISSUE TITLE
it did something when I opened It when the show started 

### ISSUE THREAD

**Issue by healur** [Exaphis/HackQ-Trivia#13]
<img width="706" alt="screen shot 2018-03-10 at 8 04 04 pm" src="https://user-images.githubusercontent.com/37125581/37249711-291dc72c-24b2-11e8-84db-aea0447db897.png">

**Comment by Exaphis** [comment]
Have you entered the correct user ID/bearer token?

**Comment by healur** [comment]
yea but I went into it and they were erased I don't know why but I just rebut them in do they delete after some time?

**Comment by Exaphis** [comment]
They should not delete. You may have erased it if you cloned the repository again.

**Comment by healur** [comment]
I think I might have but thanks
