### ISSUE TITLE
Need help setting up will pay $20

### ISSUE THREAD

**Issue by blazeresells** [Exaphis/HackQ-Trivia#130]
If anyone can join a call with me on discord and help me set this up i will pay you $20 please someone help!

**Comment by U-r-Unknown** [comment]
mail me at onlineuse321@gmail.com. i wil do it for u

**Comment by blazeresells** [comment]
@U-r-Unknown do you have discord?

**Comment by U-r-Unknown** [comment]
Ya i have but don't use. I can help u step by step

**Comment by BesiHyseni** [comment]
Discord me: BesiHyseni#1405

**Comment by U-r-Unknown** [comment]
It would be easy for me if u come in WhatsApp. Shall I give my number

**Comment by Mineleague** [comment]
I may be help, I have been investigating some issues on this code for a week or so.

**Comment by Exaphis** [comment]
Read the README and let me know if you have any specific problems.
