### ISSUE TITLE
request for step by step guide

### ISSUE THREAD

**Issue by anubhav1801** [Exaphis/HackQ-Trivia#136]
Can anyone explain me step by step installation process? I'm a bit new to these stuff...

**Comment by U-r-Unknown** [comment]
whatsapp me at +1 3154172418. i will try to help u

**Comment by blazeresells** [comment]
@U-r-Unknown can you help me also

**Comment by U-r-Unknown** [comment]
Yes blazerresells. WhatsApp me to that number or mail at onlineuse321@gmail.com
