### ISSUE TITLE
request new project:

### ISSUE THREAD

**Issue by dabsihsay** [Exaphis/HackQ-Trivia#137]
make hq life bot k ty

**Comment by fuomag9** [comment]
sorry to hijack this, but i made one on telegram if you want http://t.me/HQLifeBot

**Comment by dabsihsay** [comment]
@fuomag9 Do you have one for discord?

**Comment by fuomag9** [comment]
I've never coded discord bots, so not at the moment

**Comment by TheKaizenWolf** [comment]
@fuomag9  Awesome bot, is it there a way to use the bot everyday instead of weekly?

**Comment by fuomag9** [comment]
Unfortunately that’s impossible because how the system works. But you could create 7 accounts (by using phone number services) and rotate them everyday
