### ISSUE TITLE
anyone have HQ us bearer token and user id, please help

### ISSUE THREAD

**Issue by pkmuz1** [Exaphis/HackQ-Trivia#141]
help please

**Comment by HypePickups** [comment]
how did U get this token

**Comment by bzhu9** [comment]
using charles

**Comment by AnushPatel** [comment]
On Charles how do you find the token?

**Comment by timcarson** [comment]
> bearer=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjkxOTM4NzYsInVzZXJuYW1lIjoicG90YXRvMjUyIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9kMnh1MWhkb21oM25yeC5jbG91ZGZyb250Lm5ldC9kZWZhdWx0X2F2YXRhcnMvVW50aXRsZWQtMV8wMDAzX3JlZC5wbmciLCJ0b2tlbiI6Ik02VURIaCIsInJvbGVzIjpbXSwiY2xpZW50IjoiaU9TLzEuMy4xMSBiOTUiLCJndWVzdElkIjpudWxsLCJ2IjoxLCJpYXQiOjE1MzEzNTI1NzEsImV4cCI6MTUzOTEyODU3MSwiaXNzIjoiaHlwZXF1aXovMSJ9.4cd8DxHjM7t_gb20G1g3TXfr3oH2qdB6hzEjzhLBJtw
> 
> id=9193876

Pls dm me on discord or message me back my username is hqwinner125

**Comment by kkz95** [comment]
hello @timcarson  how i contact you on discord ?

**Comment by timcarson** [comment]
Hi my username on discord is hqwinner125#5162
What’s ur username?
Thanks :)

________________________________
