### ISSUE TITLE
HQ Germany - bearer token

### ISSUE THREAD

**Issue by patrykmaron** [Exaphis/HackQ-Trivia#142]
Anyone can get us a bearer token for HQ Germany?

**Comment by vocabexpresshaxer** [comment]
I have, but I'm selling it for £15

Email me at caffiene0addict0420@gmail.com

**Comment by mustafahafidi** [comment]
@patrykmaron here's one, don't pay no one (shame on you @vocabexpresshaxer): eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIxMTMwNjAxLCJ1c2VybmFtZSI6Imdlcm1hbmNyYXliYXMiLCJhdmF0YXJVcmwiOiJzMzovL2h5cGVzcGFjZS1xdWl6L2EvYmQvMjExMzA2MDEtSm4waEpaLmpwZyIsInRva2VuIjoiREVzRzI5Iiwicm9sZXMiOltdLCJjbGllbnQiOiIiLCJndWVzdElkIjpudWxsLCJ2IjoxLCJpYXQiOjE1MzAyODU2MzIsImV4cCI6MTUzODA2MTYzMiwiaXNzIjoiaHlwZXF1aXovMSJ9.WV_ECaV0WsmbFG5JphiIsSeGvYrfCWR10xHzpeWvfAw
