### ISSUE TITLE
Server Response not JSON issue

### ISSUE THREAD

**Issue by lordofthearcade** [Exaphis/HackQ-Trivia#148]
The bot is great and has been working for several months when all of the sudden each game "Server Response not JSON" appears? Any ideas or suggestions? Thanks!
<img width="831" alt="screen shot 2018-07-16 at 9 15 13 pm" src="https://user-images.githubusercontent.com/37389103/42791256-97822448-893d-11e8-8544-8e7f725f99a8.png">

**Comment by Silverfin13** [comment]
What happens when connecting outside a game?

**Comment by Mineleague** [comment]
Replace the fetch script (under "print ('getting')") with this:
`main_url = "https://api-quiz.hype.space/shows/now?type="
main_url = "https://api-quiz.hype.space/shows/now?type="
main_urldata = str(urllib.request.urlopen(main_url).read())
main_urldata = main_urldata.replace("b'", "")
main_urldata = main_urldata.replace("'", "")
main_urldata = main_urldata.replace('\\n', '\n')
responseJSON = json.loads(main_urldata)`
This correctly formats the data in JSON format from the website

**Comment by Riazable** [comment]
I'm running the discord bot and im getting this error: 

@everyone Show active, connecting to socket at {socket}
Server response not JSON, retrying...
0, message='Attempt to decode JSON with unexpected mimetype: '

is there anyway I can fix this? thanks

**Comment by bacondude3** [comment]
@Mineleague Sorry to bother you, but I was wondering if you could elaborate on the solution provided above. When I try to replicate that I end up breaking the code as __json__ in the line 'main_urldata = main_urldata.replace('\\n', '\n') responseJSON = json.loads(main_urldata)' is considered undefined.


Thanks again, 
                      Bacon.

**Comment by Mineleague** [comment]
Sorry, I may have formatted the above code incorrectly, try this:
`main_url = "https://api-quiz.hype.space/shows/now?type=" `
`main_urldata = str(urllib.request.urlopen(main_url).read()) `
`main_urldata = main_urldata.replace("b'", "") `
`main_urldata = main_urldata.replace("'", "") `
`main_urldata = main_urldata.replace('\\n', '\n')` 
`responseJSON = json.loads(main_urldata)`

**Comment by Riazable** [comment]
is this in hq_main.py?

**Comment by lordofthearcade** [comment]
Thanks for responding also! @shahobm The same thing happens when I start the program at a non live time. It will start up display the time...and within 30 seconds it displays the same JSON message
@Mineleague I also am having a similar issue as bacondude3...and the code does not work correctly.
Thanks!

**Comment by Mineleague** [comment]
Yes indeed @bacondude3 , it will require you to "import urllib" at the top of the file. I am considering making a pull request for this issue as it seems quite consistent throughout the issues page.

**Comment by Riazable** [comment]
@Mineleague is this in the hq_main file under main_url?

**Comment by Mineleague** [comment]
Yes, I believe so. Just import urllib at the very top of the hq_main script, and replace the other scraping code with the one I have shared. If you have any more issues, please contact me as I am willing to help.

**Comment by bacondude3** [comment]
HEY IT WORKED THANKS SO MUCH, BUT FOR EVERYONE ELSE. If you use the solution above you have to also import json at the top or else its undefined.

**Comment by Exaphis** [comment]
@Mineleague Thanks for all the help you are providing. Would you mind making a pull request with your fix so that it can be implemented by default? I currently am busy and do not have access to a bearer token to test.

**Comment by Riazable** [comment]
Could you send us you code?

**Comment by Riazable** [comment]
@bacondude can u show me your code?

**Comment by Riazable** [comment]
@Mineleague @bacondude3 So far i've done this and imported json and urllib at the top of the code.

        main_url = f"https://api-quiz.hype.space/shows/now?type=hq&userId={USER_ID}"
        main_urldata = str(urllib.request.urlopen(main_url).read())
        main_urldata = main_urldata.replace("b'", "")
        main_urldata = main_urldata.replace("'", "")
        main_urldata = main_urldata.replace('\\n', '\n')
        responseJSON = json.loads(main_urldata)
        headers = {"Authorization": f"Bearer {BEARER_TOKEN}",
                   "x-hq-client": "Android/1.3.0"}
        # "x-hq-stk": "MQ==",
        # "Connection": "Keep-Alive",
        # "User-Agent": "okhttp/3.8.0"}

Is there anything else i need to do?

**Comment by Mineleague** [comment]
You may want to remove the 'f' in line 1, but other than that you should be ok.

**Comment by Riazable** [comment]
ok thanks, looking to test this in today's UK game :)

**Comment by JasonLin1** [comment]
@Mineleague I put what you sent under getting in hq_main. Where else do i need to put the new code, you said " Be sure to also replace the fetch script in the websocket portion as well." ? (could you send a screenshot/part of code so i know where to put it)

**Comment by Mineleague** [comment]
Never mind that, I was thinking of another script, sorry about the confusion.

**Comment by Riazable** [comment]
bot just crashes everytime theres a question, would anyone be able to upload their working code? would be very helpful, thanks

**Comment by bacondude3** [comment]
Hey I'll definitely upload my code, but I did some more testing not sure if it was related to that or not. Tried running the fresh code again and it worked as well. So I'm not really sure what's up and @riazable you are running a completely diff version of this code so in your case you'd wanna keep the "f".

**Comment by Mineleague** [comment]
This could have to do with the web socket error many are having, as the socket fails to connect in some cases.

**Comment by Riazable** [comment]
you guys using logging.info or logging.debug?

**Comment by Riazable** [comment]
The bot gives answer to the first question, but then when another question is detected, it crashes and gives me this error: WARNING:lomond:disconnecting websocket please help!

**Comment by bacondude3** [comment]
I hate to pull this up again, but for a day I was good, now I'm back to the same error regardless of changing the code involving the main_url and json formatting. It starts up passes to getting and returns server response not json every 5 seconds. I've tried different bearers, changing the headers, reinstalling all dependencies, and reverting the main url back to when it included user id. All with no luck. :(

**Comment by lordofthearcade** [comment]
I think that HQ is changing the way that they deliver the questions via web socket to a device because other Github bots are also having a similar issue. A temporary solution (on mac terminal) I have found is to copy the two lines of code that start the script (cd............../HackQ-Trivia and python3 hq_main.py) or however you start the script. Right before a question is shown, paste the script and click enter. As soon as the answer is provided, click control c to end the script. Repeat this for every question. Not the best, but at least it works.

**Comment by Mineleague** [comment]
Yes, I agree. They must have changed the web socket as I can no longer even connect to it, and in the rare times I could it had no data.

**Comment by Mineleague** [comment]
I just found a major bug that may be causing all of these issues! Re-download the whole repo, and on lines 35-43 of the networking file, you need to replace the "get response" and "get json response" functions on the lines with the "aiohttp.ClientSession" ON BOTH FUNCTIONS with this:
`sync with aiohttp.ClientSession(headers=headers, connector=aiohttp.TCPConnector(verify_ssl=False)) as session:`
The issue is that the "try" function on lines ~60-65 does not show the SSL verify error that is returned, as the HQ api site does not have a valid cert (no big deal, many sites have this error). When replacing these lines, you get to disable SSL verify, returning valid data. Be sure to include the main_url solution above on the responseJSON declaration, but keep lines ~60-65 the same, only change the networking file as specifed.
Thanks for reading, Mineleague

**Comment by Riazable** [comment]
@Mineleague thank you so much, i’ll give this a go and let you know if it
works!

**Comment by Riazable** [comment]
@Mineleague sync or async? because it doesn't indent when i put sync

**Comment by Riazable** [comment]
I get 2 errors now.
1. 'WARNING:lomond:disconnecting websocket'
2. 'ERROR:asyncio:Task exception was never retrieved'
Please help!

**Comment by Riazable** [comment]
WARNING:lomond:disconnecting websocket
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<websocket_handler() done, defined at C:\Users\Jason\Desktop\HackQ-Trivia-Discord-master\networking.py:52> exception=TypeError("'>' not supported between instances of 'NoneType' and 'int'",)>
Traceback (most recent call last):
  File "C:\Users\Jason\Desktop\HackQ-Trivia-Discord-master\networking.py", line 81, in websocket_handler
    await question.answer_question(question_str, answers)
  File "C:\Users\Jason\Desktop\HackQ-Trivia-Discord-master\question.py", line 59, in answer_question
    if q_word_location > len(question) // 2 or q_word_location == -1:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Error message.

Any help would be appreciated!

**Comment by Mineleague** [comment]
I will test it out tonight at 9 PM EST and will give you an update ASAP

**Comment by Riazable** [comment]
ok cool @Mineleague

**Comment by bacondude3** [comment]
Hey, just wanted to respond as I have tested the above solution. @Riazable to answer your question it should be "async" with, I imagine that was just a typo. After editing the files I still recieve the message Server response not JSON, retrying... I don't recieve any errors that prohibit the program from running it just continuously tells me the above message. This must be specific to me because it won't even load the first question or time of next show.

**Comment by Riazable** [comment]
@bacondude3 Everything works fine for me but it won't work for the first question, I always have to restart it after I get that error above, then it starts working again. Then, after a few questions I get the same error again so I have to restart over and over again. Once someone has a fully working code, please be sure to post it here, it would be very helpful, thanks.

**Comment by bacondude3** [comment]
Yeah absolutely, and I would just like to add an update I just started it again and now its showing the next show time I literally have no idea what is happening and why it works sometimes and not others. I might just keep it running till 9pm haha.

**Comment by Riazable** [comment]
@bacondude3 probably the best thing to do lmao, we'll see how this game goes but i'm pretty sure the same thing will happen for me like in did in the UK game

**Comment by bacondude3** [comment]
Hey guys I'd like to update and apologize for stringing this out. I have discovered my issue, however it probably isn't related to anyone elses. I'm using a personal hotspot and for some reason after doing some digging around I've found that it blocks me from connecting when I run the HackQ file. However, using my internet connection works and I didn't recieve any errors whatsoever aside from my internet taking too long to process the google requests. Thanks for the all the help and contributions!

**Comment by Riazable** [comment]
Great to hear that it’s been working for you now aha. Would you be able to
send your code?

**Comment by Riazable** [comment]
@bacondude3 You got discord?

**Comment by Riazable** [comment]
@Mineleague Any updates?

**Comment by lakings323** [comment]
Any solutions???

**Comment by Riazable** [comment]
I keep disconnecting from the websocket throughout the game :/

**Comment by bacondude3** [comment]
hey yeah, I have discord.

**Comment by lakings323** [comment]
No solutions yet? Will this trivia bot ever get an update?

**Comment by Exaphis** [comment]
Try the new version, can't seem to replicate this issue. Let me know if this still happens.
