### ISSUE TITLE
Server response not JSON, retrying... 0, message='Attempt to decode JSON with unexpected mimetype: '

### ISSUE THREAD

**Issue by Riazable** [Exaphis/HackQ-Trivia#150]
How do i fix this???

**Comment by Riazable** [comment]
I'm trying to run the discord bot and i'm getting this error on discord

**Comment by Riazable** [comment]
@everyone Show active, connecting to socket at {socket}
Server response not JSON, retrying...
0, message='Attempt to decode JSON with unexpected mimetype: '

**Comment by Mineleague** [comment]
See https://github.com/Exaphis/HackQ-Trivia/issues/148 @Riazable
