### ISSUE TITLE
Traceback error?

### ISSUE THREAD

**Issue by lakings323** [Exaphis/HackQ-Trivia#153]
Hi I've never had any issues with the bot however this is the first error I have faced after typing python hq_main.py this is what came back as an error 

Traceback (most recent call last):
  File "hq_main.py", line 49, in <module>
    raise RuntimeError("Connection settings invalid")
RuntimeError: Connection settings invalid

I don't know if any of you have had any similar issues but if there is a way to fix it please comment below and if you have no idea can you please give me a step by step instruction on how to uninstall and reinstall everything, thanks!

**Comment by bacondude3** [comment]
I would check your bearer token again and make sure its valid, they expire after 3 months

**Comment by bacondude3** [comment]
you can check it here https://jwt.io/

**Comment by lakings323** [comment]
Thank you I believe that was the issue I used a bearer token I found here not really sure how to create one myself
