### ISSUE TITLE
When i try to connect to the websocket i get this

### ISSUE THREAD

**Issue by SharpBit** [Exaphis/HackQ-Trivia#156]
```
Connecting(url='https://ws-quiz.hype.space/ws/46541')
Connected(url='https://ws-quiz.hype.space/ws/46541')
Rejected(response=<response HTTP/1.1 503 Service Temporarily Unavailable>, reason='Websocket upgrade failed (code=503)')
Disconnected(reason='closed', graceful=True)
Socket closed
```
Is anyone else getting this? It seems not. How do i fix this? nothing shows up on google

**Comment by SharpBit** [comment]
Sorry for this but i've been stuck on this for days now and this project was last updated months ago so @Exaphis do you know this? (since u made it)

**Comment by Exaphis** [comment]
The bot still works perfectly for me. Does this issue occur on another network?

**Comment by SharpBit** [comment]
I figured it out. Forgot to replace https with wss 🤦‍♀️

**Comment by Exaphis** [comment]
Great! Thanks for letting me know.
