### ISSUE TITLE
Exctracting the Bearer Token from Charles

### ISSUE THREAD

**Issue by Secondlong** [Exaphis/HackQ-Trivia#157]
im trying like for 4 hours to find out how to extract the bearer code from charles, i can see traffic comming in, but i dont know where i need to click then, i always see this traffic when i open HQ on phone https://api-quiz.hype.space and the i click on it.. at this point i dont know where the bearer token should be located at..
also nothing found in google lol
please help me

**Comment by shahobm** [comment]
It depends what phone you're using, android security settings may have recently made extracting stream data with Charles impossible. It can however be done directly on a rooted android phone. Otherwise get a bearer token from a friend or one that has been posted publicly.

**Comment by Exaphis** [comment]
Try using an Android emulator, such as MEmu, to extract the bearer token.

**Comment by Gideon357** [comment]
There is also a [python script](https://github.com/Mandruyd/HQ-Token/blob/master/hq_token.py) for doing that. I suggest adding this to the README, as this is easier than charles.
