### ISSUE TITLE
timeout 

### ISSUE THREAD

**Issue by riju89** [Exaphis/HackQ-Trivia#159]
Question detected.
Question 5 out of 6
[36mWhich of these Emmy-winning comedies famously features money kept in a banana stand?
['Arrested Development', 'Will & Grace', 'Everybody Loves Raymond'][0m

Searching
['Arrested Development', 'Will  Grace', 'Will   Grace', 'Everybody Loves Raymond']
['emmy', 'winning', 'comedies', 'famously', 'features', 'money', 'kept', 'banana', 'stand']
Server timeout/error to https://www.google.com/search?q=emmy+winning+comedies+famously+features+money+kept+banana+stand&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
[]
Running method 1
{'arrested development': 0, 'will  grace': 0, 'will   grace': 0, 'everybody loves raymond': 0}
Running method 2
{'Arrested Development': {'arrested': 0, 'development': 0}, 'Will  Grace': {'grace': 0}, 'Will   Grace': {'grace': 0}, 'Everybody Loves Raymond': {'everybody': 0, 'loves': 0, 'raymond': 0}}
[('Which', 'NNP'), ('of', 'IN'), ('these', 'DT'), ('Emmy-winning', 'JJ'), ('comedies', 'NNS'), ('famously', 'RB'), ('features', 'VBZ'), ('money', 'NN'), ('kept', 'NN'), ('in', 'IN'), ('a', 'DT'), ('banana', 'NN'), ('stand', 'NN'), ('?', '.')]
Question nouns: {'banana stand'}
Running method 3
Server timeout/error to https://www.google.com/search?q=Arrested Development&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
Server timeout/error to https://www.google.com/search?q=Will & Grace&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
Server timeout/error to https://www.google.com/search?q=Everybody Loves Raymond&ie=utf-8&oe=utf-8&client=firefox-b-1-ab
Search processed
URLs fetched

Arrested Development: {}
Will & Grace: {}
Everybody Loves Raymond: {}

Keyword scores: {'Arrested Development': 0, 'Will & Grace': 0, 'Everybody Loves Raymond': 0}
Noun scores: {'Arrested Development': 0, 'Will & Grace': 0, 'Everybody Loves Raymond': 0}
[32m[0m
Search took 0.1692519187927246 seconds

**Comment by Rounak50** [comment]
@Exaphis plz help me

**Comment by chanx74** [comment]
From which trivia app did you get this
And is this text sniff taken when quiz was live?

**Comment by chanx74** [comment]
Is this from mega quiz of HQ

**Comment by Rounak50** [comment]
yes @chanx74

**Comment by Exaphis** [comment]
Now using Google's CSE API, so that problem should be fixed.
