### ISSUE TITLE
Getting 0 result

### ISSUE THREAD

**Issue by pk372** [Exaphis/HackQ-Trivia#162]
Getting 0 result  each time .all method giving 0 result.

**Comment by zcpnate** [comment]
same issue!

**Comment by lordofthearcade** [comment]
Also getting the same issue

**Comment by pk372** [comment]
It seems Google asking for captcha.so bot not able to search

**Comment by ActionLJackson** [comment]
yeah, someone needs to fork a fix to use google search API or another search company

**Comment by Exaphis** [comment]
Now using Google's CSE API.
