### ISSUE TITLE
0 Result not using google CSE API

### ISSUE THREAD

**Issue by getmoneyyoshi** [Exaphis/HackQ-Trivia#165]
The script returns zero results because is not using google API.

```
#Could use Google's Custom Search API here, limit of 100 queries per day 
    #result = service.cse().list(q=question, cx='YOUR ID HERE', num=num_results).execute()
    #return result["items"]
    page = await networking.get_response(GOOGLE_URL.format(question), timeout=5, headers=HEADERS)
    return get_google_links(page, num_results)
```

I've seen this question has been asked but not answered.  This code snippet is inside the search.py file. @Exaphis sorry to bother, but what can i do to implement this? Simply remove the pound symbols from result and return, enter my CX value??

**Comment by Exaphis** [comment]
Now using Google's CSE API, see instructions in the README.
