### ISSUE TITLE
Configuration error?

### ISSUE THREAD

**Issue by mhornblower** [Exaphis/HackQ-Trivia#167]
Not sure what is missing here - installed via clone, changed to the correct directory, pip-ed in the requirements, but when executing with Python 3 it craps out.  Traceback shows:

  File "hq_main.py", line 13, in <module>
    from hackq_trivia.config import config
ModuleNotFoundError: No module named 'hackq_trivia'

**Comment by Exaphis** [comment]
Oops, probably should've tested this beforehand. Updated README instructions.

Running `python3 -m hackq_trivia.hq_main` should fix your problem.

**Comment by mhornblower** [comment]
As you surmised, this fixed the problem.
