### ISSUE TITLE
facing this issue when try to run your code 

### ISSUE THREAD

**Issue by sanjaya740** [Exaphis/HackQ-Trivia#168]
![image](https://user-images.githubusercontent.com/43582314/65563148-43e12e80-df66-11e9-94d3-c6995824d2e5.png)

**Comment by Exaphis** [comment]
Try updating `aiohttp`.

**Comment by sanjaya740** [comment]
i fixed it by changing ensure_future = asyncio.async to ensure_future = asyncio.ensure_future in helpers.py hope it works in live game :)

**Comment by Exaphis** [comment]
Great, thanks for letting me know how you fixed it!
