### ISSUE TITLE
This is probably an easy fix problem

### ISSUE THREAD

**Issue by dogewantmoney** [Exaphis/HackQ-Trivia#17]
I am having trouble figuring out what a bearer token and user id is, and how I can find them. Everything else works perfectly normal. If you could help me out by telling me how to find them and sniff a phone server, or even just giving me a link to a tutorial that would be nice. Thank You.

**Comment by Exaphis** [comment]
gjacob314's https://github.com/gjacobs314/HQTrivia has two sample bearer tokens and user IDs you can use.
