### ISSUE TITLE
No module hackq_trivia

### ISSUE THREAD

**Issue by vishu002** [Exaphis/HackQ-Trivia#171]
![Capture2](https://user-images.githubusercontent.com/52373276/82688160-0314f300-9c76-11ea-9885-3100209fb61e.PNG)

**Comment by vishu002** [comment]
how to solve in this problem

**Comment by Exaphis** [comment]
Try running it from command line using the instructions in the README.

**Comment by vishu002** [comment]
Sir please solve this script and make update.

**Comment by vishu002** [comment]
See my problem
![Capture6](https://user-images.githubusercontent.com/52373276/82733856-83019280-9d34-11ea-966c-a1bdbefdb29f.PNG)

**Comment by Exaphis** [comment]
I'm unable to reproduce this issue. Try downloading the repository again and running the commands specified in the README instead of using IDLE.

**Comment by vishu002** [comment]
Sir you solved

**Comment by vishu002** [comment]
sir i am added bearer token then  i am run cmd showing your bearer token is invalid.
![Capture](https://user-images.githubusercontent.com/52373276/82734931-c14e8000-9d3b-11ea-92b0-f55023373f9c.PNG)

**Comment by Exaphis** [comment]
Looks like your bearer token is formatted incorrectly. You can verify it is a valid JSON web token at https://jwt.io/. Maybe you made a mistake copying it?

**Comment by vishu002** [comment]
hello sir i am add token in this website result showing "invalid signature
" sir can you give me correct bearer token please.

**Comment by vishu002** [comment]
sir i get new bearer token but not work sir same problem.

**Comment by Exaphis** [comment]
Paste your bearer into https://jwt.io/. Does it show your username/etc. correctly?

**Comment by vishu002** [comment]
Yes sir it's correctly my username

**Comment by vishu002** [comment]
sir solve this problem
my correct bearer token and username also correct.

**Comment by vishu002** [comment]
sir its work
but sir one problem show server is not response.

**Comment by Exaphis** [comment]
Could you send me a screenshot of the problem? Another option would be to send me your bearer token via email so I can help you debug.

**Comment by vishu002** [comment]
sir its work showing server not response not authorized.
![Capture](https://user-images.githubusercontent.com/52373276/82736605-afbfa500-9d48-11ea-917c-f0e7a02c49d5.PNG)

**Comment by vishu002** [comment]
sir its work show server not response.
![Capture](https://user-images.githubusercontent.com/52373276/82736644-0200c600-9d49-11ea-9f1d-703066d6a964.PNG)

**Comment by vishu002** [comment]
hello sir i am run cmd show error in server response : not authorized sir solve this problem

**Comment by Exaphis** [comment]
I'm still unable to recreate this issue. I just obtained my own bearer token and the tool works correctly.

**Comment by vishu002** [comment]
sir now bearer token is work but sir showing "WARNING : error server
response : not authorized"

**Comment by Exaphis** [comment]
Could you send me the bearer token via private email? My bearer token works just fine.

**Comment by vishu002** [comment]
sir this my private email can you give me your private email please

**Comment by Exaphis** [comment]
It is kevin@kevinniuwu.com.

**Comment by vishu002** [comment]
sir i reply you.

**Comment by Exaphis** [comment]
Solved in email. Solution was installing a VPN.
