### ISSUE TITLE
Could Not Find Module

### ISSUE THREAD

**Issue by ViralCyral** [Exaphis/HackQ-Trivia#173]
hackq_trivia> python3 -m hackq_trivia.hq_main
C:\Users\Yuzz\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe: Error while finding module specification for 'hackq_trivia.hq_main' (ModuleNotFoundError: No module named 'hackq_trivia')
C:\Users\Yuzz\Desktop\New folder\HackQ-Trivia\hackq_trivia>

**Comment by ViralCyral** [comment]
Now I cannot import any of the modules I have installed.

**Comment by Exaphis** [comment]
I believe you should be in the HackQ-Trivia folder, not the hackq_trivia folder.

**Comment by Exaphis** [comment]
Assuming resolved.
