### ISSUE TITLE
Method 3 add & Bing search

### ISSUE THREAD

**Issue by vishu002** [Exaphis/HackQ-Trivia#174]
Hello sir add methed 3 count in all answers sentence and add Bing search engine.

**Comment by Exaphis** [comment]
Could you explain "count in all answers sentence" a bit more?

**Comment by vishu002** [comment]
Option:- Oklahoma City 
Example count answers :- Oklahoma : 12   City : 3

**Comment by Exaphis** [comment]
Got it, thanks.

**Comment by vishu002** [comment]
Wel sir

**Comment by vishu002** [comment]
When you make update method 3 & Bing.

**Comment by Exaphis** [comment]
Check out the bing-search feature branch. Let me know if there are any problems.

**Comment by Exaphis** [comment]
Also, how is your proposed method 3 different from the existing method 2?

**Comment by vishu002** [comment]
Yes sir please add method 3

**Comment by vishu002** [comment]
Sir full sentence not give answers next method 3 give answer.

**Comment by Exaphis** [comment]
I don't think I get it. Could you give me another example?

**Comment by Exaphis** [comment]
No response, assuming resolved.
