### ISSUE TITLE
Error while finding module specification for 'hackq_trivia.hq_main' (ModuleNotFoundError: No module named 'hackq_trivia')

### ISSUE THREAD

**Issue by HumanCodingMachine** [Exaphis/HackQ-Trivia#176]
Error while finding module specification for 'hackq_trivia.hq_main' (ModuleNotFoundError: No module named 'hackq_trivia').

Any fix?

**Comment by HumanCodingMachine** [comment]
oduleNotFoundError: No module named 'hackq_trivia'

**Comment by Exaphis** [comment]
Are you in the directory HackQ-Trivia or hackq_trivia?

**Comment by HumanCodingMachine** [comment]
hacks_trivia,

**Comment by HumanCodingMachine** [comment]
Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

**Comment by HumanCodingMachine** [comment]
Ah, fixed.
