### ISSUE TITLE
Fixing NOT questions?

### ISSUE THREAD

**Issue by HumanCodingMachine** [Exaphis/HackQ-Trivia#180]
Any plausible method to work on not questions?

**Comment by Exaphis** [comment]
Reversed questions are handled here: https://github.com/Exaphis/HackQ-Trivia/blob/105bb1a494c06377e52762edbe7320c9dcfcf170/hackq_trivia/question_handler.py#L35 Any specific problems with this?

**Comment by Exaphis** [comment]
No response, assuming solved.
