### ISSUE TITLE
Help me please !

### ISSUE THREAD

**Issue by SunySuperman** [Exaphis/HackQ-Trivia#181]
How to fix this, show me how to fix it

![Capture](https://user-images.githubusercontent.com/45095135/86502819-a6a70680-bdd1-11ea-895e-2fe0a5827274.JPG)

**Comment by Exaphis** [comment]
Looks like something is wrong with your Google CSE API key. What happens when you run the tests in test_searcher.py?

**Comment by Exaphis** [comment]
No response, assuming solved.
