### ISSUE TITLE
getting error like error in server response: not authorized

### ISSUE THREAD

**Issue by LalitMohanSinghBohra** [Exaphis/HackQ-Trivia#182]
![image](https://user-images.githubusercontent.com/61799336/86535582-fdf6c500-befe-11ea-94c5-85367cbb7cef.png)

**Comment by LalitMohanSinghBohra** [comment]
pleas
![image](https://user-images.githubusercontent.com/61799336/86535620-38606200-beff-11ea-90f9-f363f52c7504.png)
e help

**Comment by Exaphis** [comment]
Try using a VPN, see if that works.

**Comment by LalitMohanSinghBohra** [comment]
![image](https://user-images.githubusercontent.com/61799336/86550399-e26fd680-bf5f-11ea-8287-836109785df1.png)
thanx, my dude, it worked

**Comment by LalitMohanSinghBohra** [comment]
Idont have bing key will it work the same, to get bing key it ask for credit card and I don't have one and its not accepting my debit card what to do ?

**Comment by Exaphis** [comment]
It will work with either Bing or Google. You must use one of the two.

**Comment by LalitMohanSinghBohra** [comment]
![image](https://user-images.githubusercontent.com/61799336/86806667-b440e280-c096-11ea-8a59-f68a15172e18.png)
It was running good today now again some its showing error.

**Comment by Exaphis** [comment]
Is this happening every time you run the program? Could you try this on a different network?

**Comment by LalitMohanSinghBohra** [comment]
![image](https://user-images.githubusercontent.com/61799336/86863161-43c2b180-c0e8-11ea-8fc5-ce82ba3d2ce7.png)
I am again able to run it but it didn't show answer its only show timing.

**Comment by Exaphis** [comment]
You should be using Python 3.7 or above, not Python 3.6.

**Comment by LalitMohanSinghBohra** [comment]
![image](https://user-images.githubusercontent.com/61799336/86987015-a97b7000-c1b2-11ea-8629-11a4233c6468.png)
it was running and all but it was not giving answer at all when the time was over then it provided answer just like in actual game.

**Comment by Exaphis** [comment]
Can you post your data.log file?

**Comment by LalitMohanSinghBohra** [comment]
[data.log](https://github.com/Exaphis/HackQ-Trivia/files/4894186/data.log)

**Comment by Exaphis** [comment]
You are most likely hitting the 1.5 second fetch timeout for the webpages. Increasing the timeout value in `hq_config.conf` might help.

f87b5007 should clarify if it is a timeout or error. Get the new version and try again.

**Comment by LalitMohanSinghBohra** [comment]
how can I see if its working or not before the live game?

**Comment by Exaphis** [comment]
You can test out a custom question in https://github.com/Exaphis/HackQ-Trivia/blob/master/hackq_trivia/tests/test_question_handler_answers.py.

**Comment by LalitMohanSinghBohra** [comment]
whats the command for cmd  that I cant figure it out

**Comment by LalitMohanSinghBohra** [comment]
You can test out a custom question in https://github.com/Exaphis/HackQ-Trivia/blob/master/hackq_trivia/tests/test_question_handler_answers.py.
what's the command for test custom question?

**Comment by Exaphis** [comment]
`python3 -m hackq_trivia.tests.test_question_handler_answers`

**Comment by LalitMohanSinghBohra** [comment]
![image](https://user-images.githubusercontent.com/61799336/87215105-b46c0700-c350-11ea-99c2-48ee8fb8a66e.png)
its giving answer now but it is giving some error too

**Comment by Exaphis** [comment]
Might not affect the actual script. Let me know if this happens during a live show.

**Comment by Exaphis** [comment]
No response, assuming solved.
