### ISSUE TITLE
Help me, i try python -m hackq_trivia.tests.test_question_handler_answers

### ISSUE THREAD

**Issue by SunySuperman** [Exaphis/HackQ-Trivia#184]
![image](https://user-images.githubusercontent.com/45095135/87572390-a83bcd00-c6f5-11ea-9ff7-1f9f4b2cc4c1.png)

**Comment by Exaphis** [comment]
Pull the new version, try the tests again, and post your data.log file here.

**Comment by Exaphis** [comment]
No response, assuming solved.
