### ISSUE TITLE
help

### ISSUE THREAD

**Issue by HarshitGarg-2002** [Exaphis/HackQ-Trivia#187]
<img width="682" alt="Screenshot 2020-07-17 at 10 55 43 PM" src="https://user-images.githubusercontent.com/65566086/87814105-c124b980-c880-11ea-8d4e-bb4e770a8f17.png">
please help

**Comment by HarshitGarg-2002** [comment]
![Screenshot 2020-07-17 at 11 00 20 PM](https://user-images.githubusercontent.com/65566086/87814416-532cc200-c881-11ea-8d4e-47f970457cca.png)
also this
![Screenshot 2020-07-17 at 11 00 17 PM](https://user-images.githubusercontent.com/65566086/87814431-5c1d9380-c881-11ea-87aa-9aa22c6b3059.png)

**Comment by Exaphis** [comment]
From your error message, you have to run `xcode-select --install`.

**Comment by HarshitGarg-2002** [comment]
![1595010331236463665359155930515](https://user-images.githubusercontent.com/65566086/87818909-0816ad00-c889-11ea-960e-bc9fba9c30a0.jpg)

**Comment by HarshitGarg-2002** [comment]
help

**Comment by Exaphis** [comment]
Try running `sudo xcode-select --reset` and then `xcode-select --install`.

**Comment by HarshitGarg-2002** [comment]
![1595011761824177671758746499117](https://user-images.githubusercontent.com/65566086/87820801-5c6f5c00-c88c-11ea-93a0-cee01ff01cde.jpg)
Still

**Comment by HarshitGarg-2002** [comment]
But installation completed now with no error

**Comment by Exaphis** [comment]
Oh, good. Problem solved?

**Comment by HarshitGarg-2002** [comment]
Nope

**Comment by Exaphis** [comment]
What's the problem?

**Comment by HarshitGarg-2002** [comment]
![15950119526983080876699636261909](https://user-images.githubusercontent.com/65566086/87821055-d3a4f000-c88c-11ea-8720-45e33a710512.jpg)

**Comment by Exaphis** [comment]
Read the README, then run `python3 -m hackq_trivia.bearer_finder` to obtain your bearer token.

**Comment by HarshitGarg-2002** [comment]
Ok trying

**Comment by HarshitGarg-2002** [comment]
Enter your phone number, including + and country code (e.g. +14155552671)
Example: (415) 555-0171 (U.S. number) -> +14155550171
Alternatively, enter a previous verification ID: 
? +14142869827
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/devanshugarg/HackQ-Trivia/hackq_trivia/bearer_finder.py", line 65, in <module>
    main()
  File "/Users/devanshugarg/HackQ-Trivia/hackq_trivia/bearer_finder.py", line 38, in main
    verify_resp = hq_post('verifications', {'phone': phone, 'method': 'sms'})
  File "/Users/devanshugarg/HackQ-Trivia/hackq_trivia/bearer_finder.py", line 26, in hq_post
    raise HQResponseError(f'Error code {resp["errorCode"]}: {resp["error"]}')
__main__.HQResponseError: Error code 102: not authorized

**Comment by Exaphis** [comment]
Try using a VPN.

**Comment by HarshitGarg-2002** [comment]
saying this

**Comment by HarshitGarg-2002** [comment]
ok

**Comment by HarshitGarg-2002** [comment]
wait a minute installing vpn

**Comment by HarshitGarg-2002** [comment]
got my bearer token

**Comment by HarshitGarg-2002** [comment]
pasted it in config file

**Comment by HarshitGarg-2002** [comment]
what about google api and others

**Comment by Exaphis** [comment]
Follow the instructions in the README to obtain either a Bing/Google API key. If I remember correctly, you'll need a valid credit card but you won't be charged.

**Comment by HarshitGarg-2002** [comment]
you mean google console??

**Comment by HarshitGarg-2002** [comment]
Name your custom search engine and type in any valid URL in Sites to search

what is this

**Comment by Exaphis** [comment]
Name it, and add anything (e.g. https://google.com/) in sites to search. The site you add will be deleted later as part of the process.

**Comment by HarshitGarg-2002** [comment]
ok

**Comment by HarshitGarg-2002** [comment]
if i dont setup bing then??

**Comment by Exaphis** [comment]
As long as you have one of Google or Bing set up, it is OK.

**Comment by HarshitGarg-2002** [comment]
ok

**Comment by HarshitGarg-2002** [comment]
any test py??

**Comment by Exaphis** [comment]
Feel free to run any of the tests in the test folder, such as `python3 -m hackq_trivia.tests.test_question_handler_answers`.

**Comment by HarshitGarg-2002** [comment]
<img width="1214" alt="Screenshot 2020-07-18 at 12 41 29 AM" src="https://user-images.githubusercontent.com/65566086/87822649-72325080-c88f-11ea-9c59-23f5e4975dde.png">

**Comment by Exaphis** [comment]
As it says, your API key is invalid.

**Comment by HarshitGarg-2002** [comment]
i got from official website

**Comment by Exaphis** [comment]
Did you paste it in hq_config.conf?

**Comment by HarshitGarg-2002** [comment]
yup

**Comment by HarshitGarg-2002** [comment]
<img width="1552" alt="Screenshot 2020-07-18 at 12 46 07 AM" src="https://user-images.githubusercontent.com/65566086/87822973-17e5bf80-c890-11ea-85a5-0fd68faf2995.png">

**Comment by HarshitGarg-2002** [comment]
if i rum main py
<img width="1214" alt="Screenshot 2020-07-18 at 12 47 27 AM" src="https://user-images.githubusercontent.com/65566086/87823099-52e7f300-c890-11ea-9d1b-107d63903094.png">

**Comment by HarshitGarg-2002** [comment]
i resterted the terminal and guess what it worked.    thanks a lot

**Comment by Exaphis** [comment]
No problem!

**Comment by Exaphis** [comment]
Best not share your API key online :-)

If you like the project, a star would be much appreciated!

**Comment by HarshitGarg-2002** [comment]
I started it because I loved this project

**Comment by HarshitGarg-2002** [comment]
This project should be appreciated
