### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by pk372** [Exaphis/HackQ-Trivia#191]
there is two-three links are Containing WIKIPEDIA link out of 5 link ,when i test it in test_searcher. i think it may affect keyword count. is there any way to not to check WIKIPEDIA link.

**Comment by Exaphis** [comment]
To stop checking Wikipedia links, you can add code to filter out any Wikipedia URLs here:
https://github.com/Exaphis/HackQ-Trivia/blob/1888f0d59fda08b8d643e63d358eb05f808bef9a/hackq_trivia/searcher.py#L66

Optionally, increase the number of sites to search in the config to compensate for ignoring Wikipedia links. 
I'll work on a feature to ignore certain sites in search results.
