### ISSUE TITLE
NumSitesToSearch

### ISSUE THREAD

**Issue by imhuskyboi** [Exaphis/HackQ-Trivia#192]
configparser.NoOptionError: No option 'numsitestosearch' in section: 'SEARCH'

How to fix? Never had this issue. Even reinstalled the repo

**Comment by Exaphis** [comment]
Make sure `NumSitesToSearch = 5` exists in the `[SEARCH]` section of `hq_config.conf`. https://github.com/Exaphis/HackQ-Trivia/blob/1888f0d59fda08b8d643e63d358eb05f808bef9a/hackq_trivia/hq_config.conf#L10

**Comment by imhuskyboi** [comment]
thank you it worked.
