### ISSUE TITLE
just a question, what is the function that outputs the answer

### ISSUE THREAD

**Issue by imhuskyboi** [Exaphis/HackQ-Trivia#193]
refer to name. In Question_Handler, what is the function that actually outputs the answer to console?

**Comment by Exaphis** [comment]
It's here: https://github.com/Exaphis/HackQ-Trivia/blob/1888f0d59fda08b8d643e63d358eb05f808bef9a/hackq_trivia/question_handler.py#L66

`search_methods_to_use` is a list of functions, containing `__method1` and `__method2` by default. Each method logs some text and then returns the answer, which is logged as well.

**Comment by imhuskyboi** [comment]
Thanks.
