### ISSUE TITLE
Incorrect searching URL

### ISSUE THREAD

**Issue by karimbenammar** [Exaphis/HackQ-Trivia#2]
Hi, great piece of work you got, I found a problem while trying to search in the retrieved links as their **format is incorrect**:

![image](https://user-images.githubusercontent.com/29929026/36347573-ad66aa84-145a-11e8-9194-2d3e00f0b697.png)

**Comment by Exaphis** [comment]
Thanks, just fixed this issue. Google's formatting of search results must vary between machines, as it worked perfectly on mine.
