### ISSUE TITLE
Are These My Bearer/User Tokens?

### ISSUE THREAD

**Issue by ItsCresent** [Exaphis/HackQ-Trivia#20]
Ok sniffed my IPhone with success got my user packets with the info and found 2 long strings under the deviceTokens. Are these the bearer token (top) and user id (bottom)? [http://prntscr.com/iuekmr](url)

**Comment by Exaphis** [comment]
Those don't seem to be it. The bearer token should be longer and the user ID should be pretty short. https://github.com/gjacobs314/HQTrivia has sample bearer tokens and user IDs.
