### ISSUE TITLE
"Invalid challenge response"

### ISSUE THREAD

**Issue by iDerp** [Exaphis/HackQ-Trivia#24]
I keep getting this error. It also is no longer getting question answers.
![error](https://the-best-discord-bot-ever-is.derpbot.us/L4n8ezw5.png)

**Comment by Exaphis** [comment]
I am unable to reproduce this on my machine. Let me know if this occurs again.

**Comment by iDerp** [comment]
Will do

On Mar 22, 2018, at 21:44, Kevin Wu <notifications@github.com<mailto:notifications@github.com>> wrote:


I am unable to reproduce this on my machine. Let me know if this occurs again.

**Comment by Exaphis** [comment]
No response for 5 days, assuming solved. Let me know if you come across this issue again.

**Comment by kuldeeps90** [comment]
Show active, connecting to socket at {socket}
101, message='Invalid challenge response'
i got this error
