### ISSUE TITLE
asyncio error

### ISSUE THREAD

**Issue by victorbollen** [Exaphis/HackQ-Trivia#27]
I got this error, How can I solve it?

![image](https://user-images.githubusercontent.com/37829651/38025481-df5c9b6a-3288-11e8-86b3-d40a16af24c3.png)

**Comment by Exaphis** [comment]
You need to install asyncio/other dependencies. You can install them all by typing ```pip install -r requirements.txt``` with your working directory as HackQ-Trivia, or you can install them one by one with pip.
