### ISSUE TITLE
Conn settings file

### ISSUE THREAD

**Issue by EverythingTechTime** [Exaphis/HackQ-Trivia#28]
I'm confused on where to put the bearer token and the user I'd in the conn settings file. I have the file, and I have the bearer token and the user ID. I am just confused on where to put them in the file. Thanks for your help! Also, I was wondering how accurate is it?

**Comment by Exaphis** [comment]
You put them after the equals sign. The accuracy depends on the questions HQ asks, but I'd say it is around 80%.
