### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by shabbir1215** [Exaphis/HackQ-Trivia#29]
getting this error
Show active, connecting to socket at https://ws-quiz.hype.space/ws/44256
Connected
Traceback (most recent call last):
  File "C:\Users\test\Desktop\HackQ-Trivia-master\hq_main.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(networking.websocket_handler(socket, headers))
  File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\test\Desktop\HackQ-Trivia-master\networking.py", line 56, in websocket_handler
    raise RuntimeError("Connection settings invalid")
RuntimeError: Connection settings invalid

**Comment by Exaphis** [comment]
That means your connection settings are invalid. Make sure your bearer token/user ID is correct.

**Comment by shabbir1215** [comment]
U said to use the bearer token from the post and how do I find my bearer token??

**Comment by Exaphis** [comment]
Sniffing phone traffic. If you can't find yours, you can use one found in gjacob's HackQ for Swift repository: https://github.com/gjacobs314/HQTrivia.

**Comment by shabbir1215** [comment]
I used it from there and the error came up

**Comment by Exaphis** [comment]
If so, then you are pasting it wrong or pasting it in the wrong location.

**Comment by shabbir1215** [comment]
I pasted it in the place where it says bearer token I'd in side the notepad then saving it

**Comment by Exaphis** [comment]
Can you post a screenshot of it?

**Comment by shabbir1215** [comment]
nvm u right i did it wrong lemme see if it works today

**Comment by Exaphis** [comment]
Alright, best of luck.

**Comment by shabbir1215** [comment]
It worked thanks a lot man amazing work.
