### ISSUE TITLE
Recreating in Swift

### ISSUE THREAD

**Issue by gjacobs314** [Exaphis/HackQ-Trivia#3]
I am recreating this in Swift for MacOS, and have some questions.
1. Do you need the headers? Or are they only needed for getting the questions because I tried making some requests without headers and was able to retrieve basic scheduling info and prizes.
2. When making a request, are the questions located under: https://api-quiz.hype.space/shows/now?type=hq&userId=xxxxx? Using Insomnia and making a request with all the right headers and I only get basic info, is there a separate host to use for getting questions? If you could give me the URL directly to the questions/answers I would appreciate it.

I didn't understand:

`# Remove control characters in the WebSocket message`
`message = re.sub(r"[\x00-\x1f\x7f-\x9f]", "", message)`
`message_data = json.loads(message)`
`logging.info(str(message_data))`

in your Python version, so if you could clear that up for me (how to get questions/answer) I would appreciate it!

PS: I have noticed that you can still watch the game without being signed into an account so I don't think you would need authentication to do so (and user ID)...

**Comment by Exaphis** [comment]
1. I'm not sure if you need the headers or not. I put them in so HQ would be less likely to be able to differentiate between the program making the connection and an actual phone.
2. The questions are not located there. When the game is live, a socketUrl appears in the JSON and you connect to that with a WebSocket client. The server sends messages with chat messages, viewer counts, and questions/question summaries.

The replacement of control characters is needed for the JSON to be properly read. The message from the WebSocket connection is then transformed into a dictionary with json.loads, and the message data is logged to a file. 

Hope this answered your questions. Good luck!

**Comment by gjacobs314** [comment]
Ok, so I gotta find the socket url once it appears and then read from that? Then just open up the websocket? Is there only one set of questions/answers in there at a time? I haven't ever used a websocket before. How do I get it to automatically get the socket url? Does it have a constant name or something?

**Comment by Exaphis** [comment]
Yes, you read the socket URL once it appears and open a connection. The websocket server then sends a stream of messages containing JSON messages. When the show is live the socket URL appears under the "socketURL" key in the "broadcast" key of the JSON.

**Comment by gjacobs314** [comment]
So I can just deserialize the json and open a websocket with whatever is in "jsonURL"? It would be broadcast (shown in my screenshot), and then socketURL, then that URL should be opened in a websocket?
![screen shot 2018-02-19 at 1 03 14 am](https://user-images.githubusercontent.com/34612258/36364237-e3c263a0-1510-11e8-89bf-dbf4a49630b2.png)

**Comment by gjacobs314** [comment]
Also, do you have any recordings (if that is even possible) so I don't have to wait until the game tomorrow at 3? Like recordings of the traffic, etc.

**Comment by Exaphis** [comment]
Yes, that's it. A partial log file of tonight's game is here: https://pastebin.com/5fbk4vd7. The first line is the response from https://api-quiz.hype.space/shows/now?type=hq&userId=xxxxx, and the rest is from the websocket connection.

**Comment by gjacobs314** [comment]
Alright thanks, do you know any Swift? Was wondering if you know how I could sort of convert your Python code into Swift.

**Comment by Exaphis** [comment]
I don't know any Swift, sorry.

**Comment by gjacobs314** [comment]
Alright, know any way I could give this Python script a GUI? Maybe display results a little better because sometimes its hard to tell with the console, and there are often multiple possible answers with similar scores.

**Comment by Exaphis** [comment]
Agreed. Some human decision-making is still needed if the exact answer is not found in the search results to decide if the word matches are significant enough to make it the right answer, and it might not find any possible answers if the question is worded weirdly. A GUI can be made with something like tkinter or PyQT. Feel free to fork and submit a pull request if you end up making one.

**Comment by gjacobs314** [comment]
Alright, I'm gonna go to sleep, but I'll let you know what I do. I'm new to this whole GitHub thing, still figuring out how everything works.
