### ISSUE TITLE
The bot answer wrong when the question have "NOT" in the phrase

### ISSUE THREAD

**Issue by erny83pd** [Exaphis/HackQ-Trivia#30]
Example

Which of these country is NOT in Europe?

A. Spain
B. France
C. India

The correct answer is C, but the bot will definitely say A or B.
The bot need to deliver the answer that has the lowest score.

**Comment by erny83pd** [comment]
My example is also for the other negatives (don't didn't etc..etc..)

**Comment by Exaphis** [comment]
The bot does reverse answer scores if a reverse word is detected. From my experience, HQ uses "NOT", "least", and "NEVER".
