### ISSUE TITLE
Requesting a same like bot for Loco trivia

### ISSUE THREAD

**Issue by shreyas24cool** [Exaphis/HackQ-Trivia#33]
Can you please make a similar bot for Loco trivia

**Comment by danzzen** [comment]
yes, please i would be a great help.

**Comment by shreyas24cool** [comment]
Thank you will you really make such bot

**Comment by shreyas24cool** [comment]
@danzzen when will make that bot

**Comment by shreyas24cool** [comment]
@Exaphis please can you such bot for loco trivia

**Comment by nanip9997** [comment]
Instead you can use answers for loco on playstore it helps and somewhat accurate but consistently gives the wrong answer on question 8

**Comment by yapal** [comment]
Not a gud idea to use app on play store but if someone prepares bot the same way like this it would be great

**Comment by yapal** [comment]
EXAPHIS bro reply plz and if there are any guide to get websocket of an app. Plz mention here. And plz try to make it by the details I gave u in previous msg. U can make it in a day. Plz look into this n help us

**Comment by shreyas24cool** [comment]
@Exaphis bro oleAE IT FOR LOCO TRIVIA. U can make it in a day.

**Comment by Exaphis** [comment]
#47
