### ISSUE TITLE
Awesome job =)

### ISSUE THREAD

**Issue by kylegraydev** [Exaphis/HackQ-Trivia#36]
Gave this a try today, got 9/12. Impressive!

**Comment by TiNivla** [comment]
Great work, probably one of the most accurate bots out there.  A suggestion is making the answers highlighted green or some other color so that its easier to spot them.  It takes a bit of time to search for the answer between each method.

**Comment by cwiggins9** [comment]
I'm at the part where I enter my Bearer Token and UserID but have no clue what that means. Can anyone help me out? @kylegraydev @tdaddy @TiNivla @Exaphis

**Comment by U-r-Unknown** [comment]
U should enter that in "conn_settings.txt" folder of bot

**Comment by willemcvu** [comment]
@cwiggins9 Sorry, but if you don't know what that means you probably shouldn't be doing this... its pretty self-explanatory info... hint: use Charles Proxy to sniff your phone's traffic as it connects to HQ's servers, and you'll see the needed info.

**Comment by Asserio** [comment]
@tdaddy Have you won with it?
