### ISSUE TITLE
How do I find my bearer token and user id

### ISSUE THREAD

**Issue by Dave70** [Exaphis/HackQ-Trivia#38]
I tried this on the UK version this afternoon but it just said show not on, do I need my own bearer token and user id or is there a different http address to connect to the game please?

**Comment by Exaphis** [comment]
The UK version probably has a different address for connecting. I am located in the U.S., so I don't have access to it. You can find the address by sniffing the traffic of your phone and modify this program.

**Comment by doogey96** [comment]
Having a problem with this too. Currently using  packet capture on android but finding the location of the bearer token quite tricky.

**Comment by Exaphis** [comment]
See #48
