### ISSUE TITLE
String encoding problems

### ISSUE THREAD

**Issue by christopher-wong** [Exaphis/HackQ-Trivia#39]
During the last game, the `websocket_handler` threw an error when trying to print the answers it retrieved. 

`File "/Users/cwong/Desktop/Dropbox/Github/hq-hint/networking.py", line 64, in websocket_handler print(answers) UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 7: ordinal not in range(128)`

**Comment by christopher-wong** [comment]
`➜  ~ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=`

the bot's worked perfectly on 2-3 games I tested it on previously. On today's 3pm game threw the above error on q5

**Comment by Exaphis** [comment]
Great, thanks. Could you please run the following?
```
$ python3
[...]
>>> import sys, os
>>> sys.stdout.encoding
'UTF-8'
>>> os.environ.get("PYTHONIOENCODING", "")
''
```

**Comment by christopher-wong** [comment]
```
➜  ~ python3
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, os
>>> sys.stdout.encoding
'UTF-8'
>>> os.environ.get("PYTHONIOENCODING", "")
''
```

**Comment by christopher-wong** [comment]
Looks like some sort of error showed up again tonight even with the [03ef97](https://github.com/Exaphis/HackQ-Trivia/commit/03ef978e66367c7f2ff424bf3c36858857653500) changes. Didn't get a chance to screenshot it...

**Comment by Exaphis** [comment]
https://github.com/Exaphis/HackQ-Trivia/commit/03ef978e66367c7f2ff424bf3c36858857653500 wasn't meant to fix this issue. Unicode characters regularly show up in both questions and answers, and I haven't experienced this issue before.

**Comment by christopher-wong** [comment]
I'm running 3.1.1

**Comment by Exaphis** [comment]
Should be solved in https://github.com/Exaphis/HackQ-Trivia/commit/61a5b803197c663c43f46e3148adb70b4ea14649. Let me know if there are any more issues.
