### ISSUE TITLE
How to add search method 3 for added stability

### ISSUE THREAD

**Issue by gjacobs314** [Exaphis/HackQ-Trivia#4]
`best_answer = __search_method1(search_text, answers, reverse)`
    `if best_answer == "":`
        `best_answer = __search_method2(search_text, answers, reverse)`
        `# best_answer = __search_method3(question_keywords, answers, reverse)`

If I wanted to add search method 3 as well to have all of them display just to get a greater chance of answering a question correctly, could I do something like this for the answer_question function:

```python
def answer_question(question, answers):
    print("Searching")
    start = time.time()

    answers = list(map(lambda x: x.translate(punctuation_to_none), answers))

    reverse = "NOT" in question or ("least" in question.lower() and "at least" not in question.lower())
    question_keywords = search.find_keywords(question)
    print(question_keywords)
    search_results = search.search_google(" ".join(question_keywords), 5)
    print(search_results)

    # Parallelize access of found URLs
    search_text = Parallel(n_jobs=cpu_count())(delayed(get_no_punctuation_text)(url) for url in search_results)

    best_answer1 = __search_method1(search_text, answers, reverse)
    best_answer2 = __search_method2(search_text, answers, reverse)
    best_answer3 = __search_method3(question_keywords, answers, reverse)

    print("Search took {} seconds".format(time.time() - start))
    return best_answer1 + best_answer2 + best_answer3
```

and then printing this in the hq_main file:

```python
print(question.answer_question(question_s, answers))
```

or would I have to change something?

**Comment by Exaphis** [comment]
This could work if you are looking for a string with multiple possible answers being printed as a final answer. You would need to do something else if you want to get one possible answer from the three results. The current issue with search method 3 is that it may take a long time, depending on how long the 3 google searches and 9 site accesses take.

**Comment by gjacobs314** [comment]
Oh ok that is why it was commented out, hmm. I might make a new function to answer the question with method 1 and 2 and then call 3 after so the delay doesn't cause it to not show the previous two.

**Comment by Exaphis** [comment]
You could print best_answer1 and best_answer2 before you calculate best_answer3.

**Comment by gjacobs314** [comment]
Ahh in the answer_question func?

**Comment by Exaphis** [comment]
Yep, that's it.

**Comment by gjacobs314** [comment]
So I just call the print(question.answer_question(question_s, answers)) in the question.py file, specifically the answer_question func? And it'll print out fine?

**Comment by gjacobs314** [comment]
Something like this in question.py:

```python
best_answer1 = __search_method1(search_text, answers, reverse)
    print(best_answer1)

    best_answer2 = __search_method2(search_text, answers, reverse)
    print(best_answer2)

    best_answer3 = __search_method3(question_keywords, answers, reverse)
    print(best_answer3)

    print("Search took {} seconds".format(time.time() - start))
    return best_answer1 + best_answer2 + best_answer3
```

and instead of:

```python
print(question.answer_question(question_s, answers))
```

in hq_main.py, I can just call the function like this: (instead of printing whatever it returns)

```python
question.answer_question(question_s, answers)
```

**Comment by gjacobs314** [comment]
Ok, thanks!

**Comment by gjacobs314** [comment]
In hq_main should I just call the function by saying:

```python
question.answer_question(question_s, answers)
```

or do I have to keep the print?

**Comment by Exaphis** [comment]
You can do either. If you don't keep the print, you would have to print best_answer3 instead of returning it.

**Comment by gjacobs314** [comment]
Ok, gonna leave it in then, thanks!
