### ISSUE TITLE
Heartbeat?

### ISSUE THREAD

**Issue by Oxemus** [Exaphis/HackQ-Trivia#40]
I have received this while trying to run it during a show.

> getting
> 
> Show active, connecting to socket at https://ws-quiz.hype.space/ws/44342
> Traceback (most recent call last):
>   File "C:\Users\Dinge\Desktop\HackQ-Trivia-master\HackQ-Trivia-master\hq_main.py", line 51, in <module>
>     asyncio.get_event_loop().run_until_complete(networking.websocket_handler(socket, headers))
>   File "C:\Users\Dinge\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "C:\Users\Dinge\Desktop\HackQ-Trivia-master\HackQ-Trivia-master\networking.py", line 45, in websocket_handler
>     async with session.ws_connect(uri, headers=headers, heartbeat=5) as ws:
> TypeError: ws_connect() got an unexpected keyword argument 'heartbeat'

**Comment by Exaphis** [comment]
Are you using the latest version of aiohttp?

**Comment by Oxemus** [comment]
No, I was not. thank you.
