### ISSUE TITLE
how to use the steps after nltk.download("all")

### ISSUE THREAD

**Issue by beardoholic** [Exaphis/HackQ-Trivia#42]
i don't know where is the conn_settings.txt file or how to locate it. please tell me. 
second thing is whenever i use 
usage: python3 hq_main.py in python 3.6 version it shows a syntax error. 
please help me with these two steps.

**Comment by yapal** [comment]
That is in the HackQ-Trivia folder that u downloaded

**Comment by Exaphis** [comment]
#43, seems like this problem is solved.
