### ISSUE TITLE
can anyone please tell me how to add the conn_settings.txt file! help me fast 

### ISSUE THREAD

**Issue by beardoholic** [Exaphis/HackQ-Trivia#43]
please tell me how to add connection settings file and then how to add the bearer token and user id. i have the bearer token and the user id. please tell me fast

**Comment by beardoholic** [comment]
how to open HackQ folder ?

**Comment by yapal** [comment]
The folder u got downloaded from here

**Comment by Exaphis** [comment]
Seems like the original problem is solved. The slow answering may be due to your internet connection, and the bot will automatically timeout any connections after 1.5s to keep the answering fast. If that occurs for all searches, then the bot will not be able to answer correctly.
