### ISSUE TITLE
How to modify this for loco trivia

### ISSUE THREAD

**Issue by shreyas24cool** [Exaphis/HackQ-Trivia#47]
Hey I have sniffed the traffic for loco trivia. Please tell how to modify this script for loco trivia. 
It will be more helpful if you provide the modified script.

**Comment by yapal** [comment]
Share the traffic

**Comment by yapal** [comment]
Did u use Charles? Share full saved page. Are u seeing anything related to socket

**Comment by shreyas24cool** [comment]
@yapal I use ssl proxy sniffer which I downloaded from play store

**Comment by yapal** [comment]
@Exaphis Bro if possible share the script soon before making Repo as it may take to write ReadMe and all

**Comment by PoonamChohdhary1991** [comment]
Can you help me modify it for iQ live trivia app
![38467189-69981c2e-3b52-11e8-8c39-b07b92450b31](https://user-images.githubusercontent.com/36765468/38482564-69a3bd00-3bbf-11e8-86ea-63b2781656be.PNG)

**Comment by yapal** [comment]
Poonam chowdary did u got working bot for loco

**Comment by shreyas24cool** [comment]
@PoonamChohdhary1991 Can you please sniff loco trivia app traffic and post it

**Comment by PoonamChohdhary1991** [comment]
![capture2](https://user-images.githubusercontent.com/36765468/38486976-4cfced56-3bfc-11e8-84a6-6f50b8cde187.PNG)
![capture3](https://user-images.githubusercontent.com/36765468/38486982-4ea18676-3bfc-11e8-8339-38fd9dfe7e3c.PNG)
![capture4](https://user-images.githubusercontent.com/36765468/38486990-52a39110-3bfc-11e8-9242-0a24eb4bd33c.PNG)

**Comment by yapal** [comment]
Poonam bro which software did u use? In Charles I dint get these info.

**Comment by shreyas24cool** [comment]
@Exaphis so it seems that first we will have to connect to loco websocket live that is http://realtime.getloconow.com/socket.io/?E10=3&transport=polling  then we have to copy the sid which is given in response and go to websocket http://realtime.getloconow.com/socket.io/?E10=3&sid="provided sid"&transport=websocket  
And then get the questions 
Can you write script which would do this

**Comment by PoonamChohdhary1991** [comment]
@yapal I used Charles.

**Comment by PoonamChohdhary1991** [comment]
Anyone able to modify it for brain baazi or loco or iQ live? Please help how to do it

**Comment by yapal** [comment]
Poonam bro wen did u sniff traffic during game? Mine is different from urs. I'm not seeing anything related to socket in mine. Mail me @onlineuse321@gmail.com

**Comment by PoonamChohdhary1991** [comment]
Have you installed certificate in your phone

**Comment by yapal** [comment]
Yup. I did. I sniffed traffic but got something different. Did u sniff wen game was live

**Comment by shreyas24cool** [comment]
@Exaphis  it seems that first we will have to connect to loco websocket live that is http://realtime.getloconow.com/socket.io/?E10=3&transport=polling then we have to copy the sid which is given in response and go to websocket http://realtime.getloconow.com/socket.io/E10=3&sid="providedsid"&transport=websocket
And then get the questions
Can you write script which would do this

**Comment by nanip9997** [comment]
@shreyas24cool did you get the bearer token and user id if you sniffed them please post them

**Comment by Pranav-In11** [comment]
What kind of modifications would be required for making it work for loco??

**Comment by shreyas24cool** [comment]
@Pranav-In11   it seems that first we will have to connect to loco websocket live that is http://realtime.getloconow.com/socket.io/?E10=3&transport=polling then we have to copy the sid which is given in response and go to websocket http://realtime.getloconow.com/socket.io/E10=3&sid="providedsid"&transport=websocket
And then get the questions
Can you write script which would do this

**Comment by Pranav-In11** [comment]
I really don't know how to do 😅
I asked this question because I thought how  much time @Exaphis will take to modify it

**Comment by Exaphis** [comment]
Does anybody have the full JSON responses from both the initial connection and the websocket connection to Loco Trivia?

**Comment by shreyas24cool** [comment]
@Exaphis this is the zip file which contains the saved charles session of loco trivia when game was. You wil get everything you need from this
[loco.zip](https://github.com/Exaphis/HackQ-Trivia/files/1904013/loco.zip)

**Comment by Pranav-In11** [comment]
Any Progress??
@Exaphis

**Comment by Exaphis** [comment]
You can view my progress on https://github.com/Exaphis/HackLoco-Trivia/. It is not completed yet.

**Comment by Pranav-In11** [comment]
How do I get bearer token & ID
I have installed chales proxy,but if don't know how to get that token
I have also tried some YouTube video but my device doesn't shows internet connection after using this proxy.
Please help me😅😅😅@Exaphis
Thank you!

**Comment by U-r-Unknown** [comment]
@Exaphis bro any progress?

**Comment by U-r-Unknown** [comment]
Bro @exaphis any progress happening in loco trivia

**Comment by U-r-Unknown** [comment]
This is the socket.io JavaScript. https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.0/socket.io.js
Perhaps, you can try in JavaScript


(Someone posted it, look at it bro)

**Comment by U-r-Unknown** [comment]
Bro look at loco repo Shukla mentioned something related to socket.io client

**Comment by codr247** [comment]
i have been observing this app for a while now , cant seem to get to the api exactly from where the questions come. have you guys been successful in getting that link ? i did not see it anywhere in the charles proxy file that was attached here.

**Comment by Exaphis** [comment]
@U-r-Unknown Yes, I have seen it. However, I have no experience in JS and have no clue how to use the JS client in Python. The others I have tried (and have been posted to the issue in the Loco repo) don't seem to work for socket.io 2.

**Comment by codr247** [comment]
i have some experience with JS . Can you share some logs so that i can get an idea . I have already unpinned the certificates of the app to allow packet sniffing in burp.

**Comment by U-r-Unknown** [comment]
@Exaphis Please check this out. https://github.com/veo-labs/python-socketio-client

@Exaphis. Here is one more
https://pypi.org/project/socketIO-client-nexus/

**Comment by U-r-Unknown** [comment]
Is this socket.io2
https://pypi.org/project/socketIO-client-2/0.7.1/

**Comment by U-r-Unknown** [comment]
@coder247 I don't know anything related to it bro someone posted in other repo

**Comment by codr247** [comment]
@U-r-Unknown i will see if I can scrape it

**Comment by U-r-Unknown** [comment]
R u getting questions bro@exaphis. Any progress?

**Comment by U-r-Unknown** [comment]
There may be changed in app. Can any1 sniff traffic during live game n post here

**Comment by Exaphis** [comment]
@U-r-Unknown Still a work in progress. Seems like many socket.io clients for Python are not well maintained, encountering some issues that are posted in Github but not resolved.

**Comment by Exaphis** [comment]
Sure. The main problem I am encountering is nexus-devs/socketIO-client-2.0.3/issues/2. In the meantime, I will be porting this over to Java to use socket.io's official client there.

**Comment by U-r-Unknown** [comment]
Is Java working bro?

**Comment by SinghSimranjeet** [comment]
@PoonamChohdhary1991 Hey , can you tell me how did you got that traffic to show?

**Comment by U-r-Unknown** [comment]
Bro any updates? Waiting for ur reply. Plz help

**Comment by ssahaxd** [comment]
I am able to connect to Loco's WebSocket, but it is little different from HQ's WebSocket, I need to keep talking with the server to stay connected if I stopped sending messages after 10 sec it automatically disconnects me,
@shreyas24cool Charles session helped me in this work, after connecting to the socket I have to send '2probe' to the server after that the server reply with '3probe', then I can send '5' to get the current online user numbers.
I don't have any idea how to get the questions and answers.
If anyone have Brain Baazi's packets please post I want to try that too,

**Comment by mrnoob69** [comment]
@shreyas24cool @PoonamChohdhary1991 @U-r-Unknown @nanip9997 u guys have bearer and user id of loco?

**Comment by EHAT** [comment]
any one give python script for practice loco automatically playing.
if enter 20 practice loco games ,then select whatever answers option and finally get some coins...please provide me

**Comment by EHAT** [comment]
loco 4.2.6 version app sniffing with python script send me link.

**Comment by EHAT** [comment]
practice loco coins game python script is available please put on?

**Comment by EHAT** [comment]
> Hey I have sniffed the traffic for loco trivia. Please tell how to modify this script for loco trivia.
> It will be more helpful if you provide the modified script.

please provide loco coins game python script

**Comment by EHAT** [comment]
> Does anybody have the full JSON responses from both the initial connection and the websocket connection to Loco Trivia?

please send python script for loco coins game.

**Comment by MaheshMahi19** [comment]
@Exaphis I Just tried to connect loco websocket using but its Just connecting and  closing itself... any help....?
 :)

**Comment by MaheshMahi19** [comment]
Hoo.. I got it. its working fine for me Loco Trivia WebSocket
