### ISSUE TITLE
HQ Trivia UK URL

### ISSUE THREAD

**Issue by doogey96** [Exaphis/HackQ-Trivia#48]
Would it be possible to amend the code slightly to use this with Cash Show?

**Comment by Dave70** [comment]
this is from the sniffed traffic, hope this helps, many thanks. 
OPTIONS rtsp://edge-hq-uk.hype.space:1935/live/wirecast_high RTSP/1.0
CSeq: 1
User-Agent: Lavf57.56.100

RTSP/1.0 200 OK
CSeq: 1
Server: Wowza Streaming Engine 4.7.3.01 build21295
Cache-Control: no-cache
Public: DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, OPTIONS, ANNOUNCE, RECORD, GET_PARAMETER
Supported: play.basic, con.persistent

DESCRIBE rtsp://edge-hq-uk.hype.space:1935/live/wirecast_high RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: Lavf57.56.100

RTSP/1.0 200 OK
CSeq: 2
Server: Wowza Streaming Engine 4.7.3.01 build21295
Cache-Control: no-cache
Expires: Wed, 4 Apr 2018 14:10:02 UTC
Content-Length: 646
Content-Base: rtsp://edge-hq-uk.hype.space:1935/live/wirecast_high/
Date: Wed, 4 Apr 2018 14:10:02 UTC
Content-Type: application/sdp
Session: 158684267;timeout=60

v=0
o=- 158684267 158684267 IN IP4 54.224.30.22
s=wowz://repeater-1a01.hype.space:1935/live/_definst_/wirecast_high
c=IN IP4 54.224.30.22
t=0 0
a=sdplang:en
a=range:npt=now-
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/44100/2
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1210
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=4D401E;sprop-parameter-sets=Z01AHpZShoX8kuApEAAAAwAQAAADAy4mABJ2AACTtL8Y4O0KFSw=,aOkzUg==
a=cliprect:0,0,360,202
a=framesize:97 202-360
a=framerate:25.0
a=control:trackID=2
SETUP rtsp://edge-hq-uk.hype.space:1935/live/wirecast_high/trackID=1 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 3
User-Agent: Lavf57.56.100
Session: 158684267

**Comment by perfectusr** [comment]
any updates with this? @Exaphis new repository?

**Comment by AlexLovesAlpacaa** [comment]
HQ Bearer (UK) : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2ODkwMTk3LCJ1c2VybmFtZSI6IklMb3ZlU3BvbmdlcyIsImF2YXRhclVybCI6InMzOi8vaHlwZXNwYWNlLXF1aXovYS9hMy8xNjg5MDE5Ny1pd1pMcmcuanBnIiwidG9rZW4iOiJnYTJnOGUiLCJyb2xlcyI6W10sImNsaWVudCI6IiIsImd1ZXN0SWQiOm51bGwsInYiOjEsImlhdCI6MTUyMzkwNzc5NSwiZXhwIjoxNTMxNjgzNzk1LCJpc3MiOiJoeXBlcXVpei8xIn0.yja1F-Y8VdjPO_GjXTXSpWweL3NQQPNnTSt_Zqaeh88

User ID (UK) : 16890197

this is a Bearer and User ID For HQ UK.

**Comment by Killerdon2** [comment]
![image](https://user-images.githubusercontent.com/38570641/39296689-7b7632b0-4939-11e8-90f0-f0214d289533.png)
