### ISSUE TITLE
can you help me modify it for iQ live trivia app

### ISSUE THREAD

**Issue by PoonamChohdhary1991** [Exaphis/HackQ-Trivia#49]
![capture1](https://user-images.githubusercontent.com/36765468/38467189-69981c2e-3b52-11e8-8c39-b07b92450b31.PNG)

**Comment by shreyas24cool** [comment]
@PoonamChohdhary1991  Can you please sniff the traffic of loco trivia appp also. Please do this and post the screenshot.

**Comment by PoonamChohdhary1991** [comment]
![capture2](https://user-images.githubusercontent.com/36765468/38486923-1347a92a-3bfc-11e8-9e36-8f1557115386.PNG)
![capture3](https://user-images.githubusercontent.com/36765468/38486939-25c07438-3bfc-11e8-9116-a3946c9849e4.PNG)
![capture4](https://user-images.githubusercontent.com/36765468/38486942-2948a508-3bfc-11e8-9507-2bf7a1dbbfc5.PNG)
