### ISSUE TITLE
Are you able to add other game shows?

### ISSUE THREAD

**Issue by Fizzy7up** [Exaphis/HackQ-Trivia#50]
The bot is working great but are you able to add other shows such as 'Cash Show', 'The Q' and 'SwagIQ'? I can share the sniffed data if that is needed?

**Comment by Exaphis** [comment]
That would be great. I know some shows have different ways of connecting, but if you could share the data here I could try to make new repositories for different shows.

**Comment by tdaddy** [comment]
would love one for hangtime or joyride

**Comment by sanjaya740** [comment]
@Fizzy7up can you share the sniff data for swag iq like live webhook api and barear token im trying to make swag iq bot
