### ISSUE TITLE
What is a Bearer Token & User ID?

### ISSUE THREAD

**Issue by cwiggins9** [Exaphis/HackQ-Trivia#51]
I'm at the step where I need to Enter a Bearer Token and UserID. I don't know how/where to find those, and what purpose they serve. Can anyone assist me?

**Comment by Fizzy7up** [comment]
You need the token and ID so the bot can essentially 'watch' the game with you and get the questions. You can get this by using charlesProxy and following a few tutorials

**Comment by cwiggins9** [comment]
@Fizzy7up Thanks I understand now! Any tutorials in specific you know of? I've downloaded Charles

**Comment by Exaphis** [comment]
What operating system is your phone using? If you can't find your bearer token/user ID, you can use gjacobs314's examples here: https://github.com/gjacobs314/HQTrivia

**Comment by cwiggins9** [comment]
@Exaphis I have a Android Tmobile Revvl Plus. Not exactly the best hah, but it's still pretty good.

**Comment by Exaphis** [comment]
Since it uses Android N, traffic can't be sniffed without modifying the app itself. You can just use the examples posted in the repo I linked above.

**Comment by cwiggins9** [comment]
@Exaphis Okay that makes sense. So I just enter the information into that notepad file, save. And then when do I run that final code sequence 'python3 hq_main.py'? When the game starts or 2 minutes before?

**Comment by Exaphis** [comment]
You can run it whenever you want. If the show is not online it will say so.

**Comment by cwiggins9** [comment]
@Exaphis 
![capture](https://user-images.githubusercontent.com/38196986/38517439-a4707dd4-3bff-11e8-9c7e-f97740b30fbc.JPG)

Was running fine before, but wont now?

**Comment by Exaphis** [comment]
Try using just ```python``` or running it from IDLE.

**Comment by cwiggins9** [comment]
weird.. it started working for me after the game had ended. I'll try it during the one tonight

**Comment by Exaphis** [comment]
No response for 10 days, assuming solved.
