### ISSUE TITLE
how can I solve this error?

### ISSUE THREAD

**Issue by iRiky237** [Exaphis/HackQ-Trivia#52]
<img width="506" alt="screen shot 2018-04-09 at 14 01 20" src="https://user-images.githubusercontent.com/36242831/38496613-82a868de-3bfe-11e8-92d8-606afe6c3881.png">

**Comment by zenolus** [comment]
got to python. enter 

>>nltk.download("stopwords")

**Comment by iRiky237** [comment]
??

**Comment by iRiky237** [comment]
<img width="480" alt="screen shot 2018-04-09 at 20 26 22" src="https://user-images.githubusercontent.com/36242831/38515374-4cb487a4-3c34-11e8-88c0-e537449a4601.png">

**Comment by Exaphis** [comment]
I have updated the README to add instructions to fix this issue. Please run ```/Applications/"Python 3.6"/"Install Certificates.command"``` in Terminal.

**Comment by iRiky237** [comment]
Okay thanks solved that.
If it says RuntimeError("Connection settings invalid")
RuntimeError: Connection settings invalid, am I good?
Do I get this error because the game isn't live yet?

**Comment by Exaphis** [comment]
That means your bearer token/user ID is incorrect.

**Comment by iRiky237** [comment]
When I sniffed the traffic under the voice token I found the line, which one should I use?

**Comment by Exaphis** [comment]
Could you post what you have here?

**Comment by iRiky237** [comment]
<img width="244" alt="screen shot 2018-04-09 at 20 43 35" src="https://user-images.githubusercontent.com/36242831/38516201-c056ceb8-3c36-11e8-8e14-ff1b09977b3f.png">

**Comment by iRiky237** [comment]
<img width="172" alt="screen shot 2018-04-09 at 20 45 39" src="https://user-images.githubusercontent.com/36242831/38516266-fda496ce-3c36-11e8-80d6-4b316bb18305.png">
Or should I use this one?

**Comment by Exaphis** [comment]
Yes, that is the correct one. You have the user ID?

**Comment by iRiky237** [comment]
Yes, now is saying show not on.
Does the user id need " " these?

**Comment by Exaphis** [comment]
The user ID does not need quotations around it in the conn_settings.txt file.

**Comment by iRiky237** [comment]
Thank you very much

**Comment by Exaphis** [comment]
Alright, seems like this problem is solved.
