### ISSUE TITLE
Cannot find bearer token and user ID

### ISSUE THREAD

**Issue by TillST123** [Exaphis/HackQ-Trivia#54]
Hi,
I have made my way through the other steps but this one has stumped me. On the other thread about this- I checked out the link you provided and still I cannot work out how to find it

**Comment by U-r-Unknown** [comment]
use gjacobs314's examples here: https://github.com/gjacobs314/HQTrivia

**Comment by JayOffical** [comment]
@U-r-Unknown I successfully got my Bearer Token, but how do I get my ID, I'm using a proxy to Fiddler at the moment.

**Comment by Exaphis** [comment]
No response from @TillST123, assuming solved.

**Comment by scaryslender18** [comment]
@U-r-Unknown I can just use someone else's example? But I thought that it was unique to each individual person.
