### ISSUE TITLE
modifying

### ISSUE THREAD

**Issue by jhonny262** [Exaphis/HackQ-Trivia#56]
Hey i wanna make it to work for the similar application it looks same but is for my country (like bootleg hqtrivia.. it looks and works i think same but makes other company from here) can you help me out to make it? it won't be popular and no one almost will use it maybe a couple of friends but it would be really amazing

**Comment by jhonny262** [comment]
app in my country is popular i meant like,,, bot wont be popular

**Comment by Exaphis** [comment]
Sorry, that isn't on my priority at the moment. Feel free to reach out later.
