### ISSUE TITLE
Easier to Read?

### ISSUE THREAD

**Issue by lordofthearcade** [Exaphis/HackQ-Trivia#57]
Awesome bot! A suggestion though is to make it a little easier to read during the game. Anyone know a way to modify it. Similar to:

question = 'The name of which common herb is taken from a Greek word connoting royalty?';
answers  = [
    'A' => 'Cilantro', // 15.79%
    'B' => 'Coriander', // 10.53%
    'C' => 'Basil', // 73.68%
];

This is the only output that is really needed for the each of the three methods

**Comment by Exaphis** [comment]
Thanks for the suggestion. I replied to it in #60.
