### ISSUE TITLE
How to get the own BEARER_TOKEN & USER_ID

### ISSUE THREAD

**Issue by RavixModz** [Exaphis/HackQ-Trivia#58]
Hello,
how can I sniff my bearer token and the user ID?
I am using an iPhone & I also have the app installed on an rooted Android emulator.

Thanks for your help 👍

**Comment by Exaphis** [comment]
Use Charles/Fiddler/any other program that allows you to view your traffic.

**Comment by U-r-Unknown** [comment]
RavixModz follow this video:
https://m.youtube.com/watch?v=2pUrhY-wYK0

**Comment by Exaphis** [comment]
No response, assuming solved.
