### ISSUE TITLE
RuntimeError: Connection settings invalid

### ISSUE THREAD

**Issue by JayOffical** [Exaphis/HackQ-Trivia#59]
It was running perfectly before the 9 pm game, where it basically told me when the next game will be. When the clock hit 9 pm I opened the program and this happened.

![capture](https://user-images.githubusercontent.com/38303714/38651219-f4e2da58-3dcd-11e8-871f-3d89823ec8ca.PNG)

@Exaphis @TiNivla

**Comment by Exaphis** [comment]
That is because your user ID/bearer token is invalid.

**Comment by JayOffical** [comment]
@Exaphis Could you explain in a little more detail how to get them, please.

**Comment by Exaphis** [comment]
Do you have the sniffed traffic?

**Comment by JayOffical** [comment]
@exaphis no. What do I need to do to have it

**Comment by JayOffical** [comment]
@Exaphis Ok, so I downloaded Telerik Fiddler and enabled decrypt HTTPS traffic but now what do I do.

**Comment by JayOffical** [comment]
@Exaphis I got my bearer token but where is the ID I can't find it anywhere
![capture](https://user-images.githubusercontent.com/38303714/38763110-062dbb34-3f63-11e8-8baf-4159aa394e01.PNG)

**Comment by Exaphis** [comment]
Now that I think about it, does the program work without the user ID (while show is live)?

**Comment by Exaphis** [comment]
No response for 9 days, assuming solved.
