### ISSUE TITLE
Reading the log as a JSON structure

### ISSUE THREAD

**Issue by gjacobs314** [Exaphis/HackQ-Trivia#6]
I am working on finishing up my Swift version of this cheat, and I was wondering if there was a way for me to read the log in a JSON type format (with all the right indentations/spacing) so that it is easy to read the structure because I can't debug when the game isn't live. Let me know if you have any programs that do this. Thanks.

**Comment by Exaphis** [comment]
You could use https://jsonformatter.curiousconcept.com/ without JSON validation as the strings in the logs are stored with single quotes.

**Comment by gjacobs314** [comment]
Alright thanks got it working, also that log is without the control characters right? I basically just have to remove

`r"[\x00-\x1f\x7f-\x9f]"`

from the websocket? Where exactly are those? I formatted the log to JSON and I don't know where the characters would be. Would it be everywhere there is text?

**Comment by Exaphis** [comment]
The characters would be invisible, as they are control characters. The data stored in the log has already been stripped of those.

**Comment by gjacobs314** [comment]
So if they are invisible I don't need to remove them? I can just read as a string and search?

**Comment by Exaphis** [comment]
If you wanted to you could search the string. For Python to read the string as a JSON, I had to strip the control characters. Even though they don't represent a written symbol, they are still there.

**Comment by gjacobs314** [comment]
Alright, any way I could try debugging getting questions/answers without the game being live?

**Comment by Exaphis** [comment]
You could feed your program the log file. You wouldn't be able to debug connecting to the HQ server without the game being live.

**Comment by gjacobs314** [comment]
Know of any way I can create a websocket myself to read from?

**Comment by Exaphis** [comment]
Yes, you can create a websocket server yourself using one of the many websocket packages out there. http://websockets.readthedocs.io/en/stable/intro.html has fairly simple instructions for creating a client/server with the websockets package in Python 3.

**Comment by gjacobs314** [comment]
Saw your update today... did you not previously use headers to get the questions/data from the socket? Also, in case you wanted to find some more search algorithms, this program did a nice job (it's in Swift though): https://github.com/DanielSmith1239/HQTriviaMaster

**Comment by Exaphis** [comment]
I was using headers with the previous websocket-client connection. I created a new branch to test a different package, but I forgot to use the headers there. That resulted in the server not giving me any information. When I merged the optimization/websocket branch into master, the commit came along with it.

I'll check out that repository soon. Thanks!

**Comment by gjacobs314** [comment]
So is what you have right now fully updated + working?

**Comment by Exaphis** [comment]
Yes, it is working.

**Comment by gjacobs314** [comment]
Alright, does print() just make a new line? Are quotes not required? I saw that and just wanted to make sure.

**Comment by Exaphis** [comment]
Print with nothing in it will make a new line.

**Comment by gjacobs314** [comment]
Alright just making sure. Tonight I'm going to test out my project and see if it correctly can connect to the WebSocket. I'll update you on what happens.

**Comment by Exaphis** [comment]
Sounds good. I'll be here to help if you have any more questions.

**Comment by gjacobs314** [comment]
Found something cool out... you probably already know it but in the WebSocket message of a question, there is a value "category," that might be helpful for searching/if you could have google categorize things or only go to sites that are a certain category.

**Comment by Exaphis** [comment]
Yep, found that out from the log files. Still need to find a way to use that though.

**Comment by gjacobs314** [comment]
Alright cool. For the websocket part, is it always open or does it only open for a moment when the question goes live then it closes? Or do you make yours close the  socket automatically?

**Comment by Exaphis** [comment]
The websocket server is only open when the game is live. The socket will close automatically when the game ends.
