### ISSUE TITLE
Can you add probability under the answers?

### ISSUE THREAD

**Issue by QuestToBeTheBest** [Exaphis/HackQ-Trivia#60]
Since you only have 10 seconds to answer, I think it would help if the probability of the answer being correct was being printed out under the answer. I color coded the answers also so I could more quickly see my options. But with probability I wouldn't have to look up at the answer count.

**Comment by JayOffical** [comment]
@QuestToBeTheBest How did you get your token ID and username. Can you explain what is sniffed traffic or how do I get it and how do I proceed from there?

**Comment by JayOffical** [comment]
@QuestToBeTheBest Ok, so I downloaded Telerik Fiddler and enabled decrypt HTTPS traffic but now what do I do.

**Comment by TiNivla** [comment]
@QuestToBeTheBest how did u color code answers?

**Comment by Exaphis** [comment]
@QuestToBeTheBest I believe what is currently printed is the most helpful. It allows you to see what the program thinks are the keywords, what is being searched, and how often each word occurs. That helps you determine if the answer is trustworthy or not. 

Would it help if I added an explanation of the outputs in the README?
