### ISSUE TITLE
Nltk.download("all")

### ISSUE THREAD

**Issue by U-r-Unknown** [Exaphis/HackQ-Trivia#61]
When downloading nltk.download("all") it stops at framenet_v17 how to solve this?
But it won't give any error message. Any way to download that manually?

**Comment by Exaphis** [comment]
Are there any errors running the program during a game?

**Comment by Exaphis** [comment]
That wouldn't be a problem with nltk. Where are you located? It may be your internet connection.

**Comment by U-r-Unknown** [comment]
Im from India. Got this when i tried running.Does this mean its working?

Server response not JSON, retrying...

Show not on.
Next show time: 2018-04-15 06:30 AM
Prize: $5,000

Show not on.
Next show time: 2018-04-15 06:30 AM
Prize: $5,000

**Comment by U-r-Unknown** [comment]
when downloading packages using command nltk.download("all") it stops at
 downloading package framenet_v17 . any method to download manually?

**Comment by U-r-Unknown** [comment]
Im from India. when i run program, I get this. Does this mean its working. For framenet_v17 it just took some time. but it downloaded all nltk data

Server response not JSON, retrying...

Server response not JSON, retrying...

Show not on.
Next show time: 2018-04-15 06:30 AM
Prize: $5,000

Server response not JSON, retrying...

Server response not JSON, retrying...

Server response not JSON, retrying...

Server response not JSON, retrying...

Server response not JSON, retrying...

Server response not JSON, retrying...

Server response not JSON, retrying...

Show not on.
Next show time: 2018-04-15 06:30 AM
Prize: $5,000

**Comment by Exaphis** [comment]
Try changing the timeout in line 28 of hq_main.py to a higher value.

**Comment by U-r-Unknown** [comment]
bro less than 5 is okay? but what about loco? How long does it take?

**Comment by U-r-Unknown** [comment]
Is loco working?

**Comment by Exaphis** [comment]
Not yet. It uses a different method to connect to the websocket (socket.io), so I have to deal with that in Python first.

**Comment by U-r-Unknown** [comment]
Did u see zip file shared by someone?

**Comment by Exaphis** [comment]
Yes, I saw the Loco Charles file.

**Comment by U-r-Unknown** [comment]
How many days may be required?

**Comment by Exaphis** [comment]
Sorry, can't give you a concrete estimate at the moment.
