### ISSUE TITLE
Connection Settings Invalid

### ISSUE THREAD

**Issue by bionichuman** [Exaphis/HackQ-Trivia#62]
I got my id and token from sniffing and put them into the txt file but it still says the connection settings are invalid?

**Comment by bionichuman** [comment]
It says then my token and Id are invalid but what makes them in valid or how do I fix it?

**Comment by Exaphis** [comment]
Could you show me your sniffed traffic?

**Comment by JayOffical** [comment]
@bionichuman I successfully got my Bearer Token, but how do I get my ID, I'm using a proxy to Fiddler at the moment.

**Comment by JayOffical** [comment]
@bionichuman 
![capture](https://user-images.githubusercontent.com/38303714/38763180-078f2a16-3f64-11e8-9845-e434ee3719f0.PNG)

**Comment by bionichuman** [comment]
@JayOffical @Exaphis Got it working but how can we make it more accurate?

**Comment by U-r-Unknown** [comment]
How many answers got correct? And which type questions answers were wrong?

**Comment by bionichuman** [comment]
@U-r-Unknown @Exaphis It got about 6/12 and I dont remember all of them that it got wrong but it got this wrong- Which of these is the highest scoring game?
Basketball
Soccer
Football

It said soccer, answer is basketball...

**Comment by JayOffical** [comment]
@bionichuman How did you get the user ID from???? I got my token but I cant figure out the token ID

**Comment by bionichuman** [comment]
@JayOffical If you got your token the id is like 2 lines under it.

**Comment by JayOffical** [comment]
@bionichuman got it from here https://github.com/DanielSmith1239/HQTriviaMaster#web-socket 👍

**Comment by Exaphis** [comment]
No response for 8 days, assuming solved.
