### ISSUE TITLE
Index Error?

### ISSUE THREAD

**Issue by bionichuman** [Exaphis/HackQ-Trivia#64]
How do I fix the error below?

![error](https://user-images.githubusercontent.com/11791504/38759002-bea49a24-3f41-11e8-834a-9849a8859b76.JPG)

**Comment by bionichuman** [comment]
@U-r-Unknown Yes, I did. I don't know why it gives me that error...

**Comment by Exaphis** [comment]
Could you post what is in your conn_settings.txt? (blur part of the bearer/user ID out if you'd like)

**Comment by TheUknown23** [comment]
i have the same issue

**Comment by TheUknown23** [comment]
here is my connectionts.txt
![screenshot 41 _censored](https://user-images.githubusercontent.com/38389931/38835709-849d59ea-4191-11e8-8527-2ea8bccced55.jpg)

**Comment by Exaphis** [comment]
Please get the most recent commit and run it again. If the same issue reoccurs, send me the log file.

**Comment by Exaphis** [comment]
No response for 7 days, assuming solved.
