### ISSUE TITLE
Tutorial Please?

### ISSUE THREAD

**Issue by AlexLovesAlpacaa** [Exaphis/HackQ-Trivia#67]
Could someone or the Owner make like a Step to step tutorial, I did read the Readme File, but I don't understand anything (I never used python never coded never done anything like this) So I would be asking if someone could help me out with a step to step tutorial on how to do it, since I'm really interested in it!

**Comment by JayOffical** [comment]
1) First, do this to get your USER ID and Bearer TOKEN:

https://github.com/DanielSmith1239/HQTriviaMaster#web-socket

2)Put those in the file conn_settings.txt without space or line in between anything

3)Open up the program 👍

**Comment by JayOffical** [comment]
@AlexLovesAlpacaa

**Comment by AlexLovesAlpacaa** [comment]
@JayOfficial
Where do I find a USER idand a BearerToken in the Site Given

**Comment by JayOffical** [comment]
BOY just follow the instructions it gives you

**Comment by Exaphis** [comment]
No response for 8 days, assuming solved.
