### ISSUE TITLE
New Issue once again

### ISSUE THREAD

**Issue by AlexLovesAlpacaa** [Exaphis/HackQ-Trivia#69]
![unbenannt](https://user-images.githubusercontent.com/38406656/38837788-9a2bfa68-41d3-11e8-88d1-3080bada3e57.PNG)
Thats the error code im getting

**Comment by TheUknown23** [comment]
I get this error as well, I think it has to do with mac rich text converting to plain text used by
notepad. What I did was reinstalled the connections txt. disabled word wrap in format options. Don't worry if the txt file is all messed up. just add your id and bearer without pressing enter. make sure there is a space after your bearer id to separate it from user id.

**Comment by Exaphis** [comment]
@TheUknown23, thanks for offering a solution. If that doesn't work, please get the most recent commit and run it again. If the same issue reoccurs, send me the log file.

**Comment by Exaphis** [comment]
No response for 7 days, assuming solved.
