### ISSUE TITLE
Freezes when PDF is found

### ISSUE THREAD

**Issue by gjacobs314** [Exaphis/HackQ-Trivia#7]
This may have just been me, but one of the sites visited was a direct link to a PDF, and it froze the program.

**Comment by gjacobs314** [comment]
Also, do you still have the earlier version of this (before the new websocket thing and without using method3)?

**Comment by Exaphis** [comment]
The PDF froze mine as well, will be looking into it.

You can checkout a different commit to get to a different state.

**Comment by Exaphis** [comment]
Fixed, PDFs will now throw an error.
