### ISSUE TITLE
FYI: Auth tokens being reset

### ISSUE THREAD

**Issue by gjacobs314** [Exaphis/HackQ-Trivia#70]
Mine was reset (I hadn't played or used the bot for a while but mine became invalid and I had to find it again). This happened yesterday so I don't know how common this will be.

**Comment by Exaphis** [comment]
I recently found out that the bearer tokens are in the form of a JSON Web Token (JWT). Your bearer token expires 3 months after it is created. On https://jwt.io/, you can enter your bearer token and find your user ID, username, token expiry date, and other information about your token.
