### ISSUE TITLE
Why are some questions not being detected and recieved? Also can you make it so the answers are color coded and stand out more?

### ISSUE THREAD

**Issue by TheUknown23** [Exaphis/HackQ-Trivia#71]
great job though, first bot that actually worked for me.

**Comment by Exaphis** [comment]
That bug does happen, but it is very rare for me. It is currently being fixed. In terms of color coding, that is on the list as well.

**Comment by Exaphis** [comment]
Color coding added in https://github.com/Exaphis/HackQ-Trivia/commit/e698ff2192c045b21583b6dbc2e086dc99c219bf.

**Comment by Exaphis** [comment]
Missing questions fixed in https://github.com/Exaphis/HackQ-Trivia/commit/73a5e82d06dd8dd9534173b49490ab20173d9e3e.
