### ISSUE TITLE
Server timeout/error to http:....

### ISSUE THREAD

**Issue by Kev9200** [Exaphis/HackQ-Trivia#72]
I keep getting this error everytime a question comes up. I know that my bearer token and ID are entered right because I used it for a different program/computer. Can anyone please help me on this?

![screenshot 40](https://user-images.githubusercontent.com/37965198/38966007-f4978230-434d-11e8-9b56-5f12092f89e7.png)
![screenshot 41](https://user-images.githubusercontent.com/37965198/38966037-23f515a6-434e-11e8-92ee-038317b48459.png)

**Comment by tdaddy** [comment]
@Kev9200 works for me most of the time. it's just certain questions when it gets 0's returned for all 3 answers that it skips to method 2. but yeah, method 1 has been far more accurate for me. i rarely listen to method 3 lol

**Comment by Kev9200** [comment]
Okay, thank you for your opinion.

**Comment by Exaphis** [comment]
Could you post your log file here?

**Comment by Betamog** [comment]
@Exaphis I Have The Same Issue (Server timeout/error to http:....) Where I Can Find my log file to post it?

**Comment by Exaphis** [comment]
It's the data.log in the HackQ-Trivia folder.

**Comment by Betamog** [comment]
[data.log](https://github.com/Exaphis/HackQ-Trivia/files/1939490/data.log)
Here it is @Exaphis

**Comment by Exaphis** [comment]
Seems like you need to increase the timeout for finding websites. I will add this as a setting in the future.
