### ISSUE TITLE
Having trouble telling which part of this string is my bearer token and which is the user ID

### ISSUE THREAD

**Issue by scaryslender18** [Exaphis/HackQ-Trivia#75]
I used mitmproxy to get this string of data from my iPod:

remember_token=aa908cd08fcbe51b2173aa4c529123ec1d568a19; _ga=GA1.2.1052999602.1514804839; _gid=GA1.2.1413795075.1524181975; **userId=5a4809abba10e6003900013e**; _vwo_uuid_v2=247682BFAB528CF903EE470F5DDCB12F\|49a75a0629133d21e920acdbb6f9c9a7; optimizelyBuckets=%7B%7D; optimizelySegments=%7B%22217547240%22%3A%22true%22%2C%22217547241%22%3A%22safari%22%2C%22220844099%22%3A%22search%22%2C%222753370110%22%3A%22none%22%7D; mp_fdc087d38e3946108eaefb862c6eb9d8_mixpanel=%7B%22distinct_id%22%3A%20%225a4809abba10e6003900013e%22%2C%22is_member%22%3A%20true%2C%22%24search_engine%22%3A%20%22google%22%2C%22%24initial_referring_domain%22%3A%20%22www.google.com%22%7D; registered_member=true; optimizelyEndUserId=oeu1514804838270r0.39303997382510414--
  
I take it that the bolded part is my userid, but I can't seem to figure out which is the bearer token. I assumed it was the remember_token, but that didn't work. Any help?

**Comment by Exaphis** [comment]
That doesn't seem like the correct format for the user ID. I normally use Charles/Fiddler, so I can't help you with mitmproxy.
