### ISSUE TITLE
people are selling your bot for money and making profits

### ISSUE THREAD

**Issue by Jimmychou2** [Exaphis/HackQ-Trivia#78]
![image](https://user-images.githubusercontent.com/37646631/39087763-f8383ab0-4573-11e8-9894-916312a35a38.png)

**Comment by AlexLovesAlpacaa** [comment]
the one in the Photo isnt Yours, i bough a bot from him, it isnt

**Comment by joshuasw** [comment]
Alex does the bot you bought work?

**Comment by botinger** [comment]
There are thousands of morons who want to make money with exaphis code..
exaphis botcode is short and genial, because easy to use and to comprehend.
