### ISSUE TITLE
Capturing bearer tokens

### ISSUE THREAD

**Issue by bobThomas512** [Exaphis/HackQ-Trivia#8]
I am trying to find my bearer token using a proxy but whenever I get the data it is just a jumbled mess. I have tried using Fiddler 2, Charles Proxy, and Postman, but whatever I do either HQ just wont load the data or when it does capture it it just looks like a bunch of random characters. Any ideas?

**Comment by Exaphis** [comment]
What phone OS are you using, and which version?

**Comment by bobThomas512** [comment]
I am using android OS on a Samsung galaxy s7. As for the HQ versions I am using the latest, 1.2.2

**Comment by Exaphis** [comment]
Are you using Android 7 or above? If you are, capturing the bearer would be impossible without rooting or decompiling the HQ app. I have not tried finding the bearer on Android 7, so I would not be able to advise you further. The process is much easier if you have an iOS device or a device with an older Android version.

**Comment by bobThomas512** [comment]
So an iphone 6 would work?

**Comment by bobThomas512** [comment]
Ok, I just tried using an iPhone 6s yet I still get bad data

**Comment by Exaphis** [comment]
Have you installed the SSL certificate? https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

**Comment by bobThomas512** [comment]
No I will try that now, will it fix it?

**Comment by Exaphis** [comment]
I think so, without the SSL certificate Charles Proxy would not be able to read the data sent to HQ.

**Comment by bobThomas512** [comment]
It still does not work, I have installed the SSL certificate. Is there anything I need to do on the PC side?

**Comment by bobThomas512** [comment]
I got it to work; Just needed to enable the certificate in settings, and add a * to the host and port in ssl settings on Charles proxy
