### ISSUE TITLE
Google API

### ISSUE THREAD

**Issue by MadddAmAdam** [Exaphis/HackQ-Trivia#83]
How would I utilize my Google custom search API here?  Still learning and have come a long way, but I don't want to mess anything up that isn't currently broken, so I'm hoping for some good advice to lead me in the right direction. :-)  Maybe an example of what the code should look like, with fake api numbers of course lol. 

  # Could use Google's Custom Search API here, limit of 100 queries per day
    # result = service.cse().list(q=question, cx=CSE_ID, num=num_results).execute()
# return result["items"]

Hope you've been doing well!! Best regards!

**Comment by Exaphis** [comment]
Yep, that should still work.

**Comment by MadddAmAdam** [comment]
Thanks ☺  where would I place my Google api?

**Comment by Exaphis** [comment]
StackOverflow is your friend here. Check out https://stackoverflow.com/questions/37083058/programmatically-searching-google-in-python-using-custom-search.

**Comment by MadddAmAdam** [comment]
Thanks! You're the best! 😎🤘🤘🤘

**Comment by asharpie** [comment]
@MadddAmAdam How did you get passed this error:

>async with session.get(url, timeout=timeout) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 843, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 273, in _request
    url = URL(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yarl/__init__.py", line 157, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be

**Comment by MadddAmAdam** [comment]
Sorry for the late reply, just noticed this! I'm not sure, I'm still learning myself and never got the Google API section correct.  I haven't really tried since then lol. Hope you've figured it out by now 😊
