### ISSUE TITLE
Syntax Error in Hq_main.py

### ISSUE THREAD

**Issue by zombotesterxyz** [Exaphis/HackQ-Trivia#84]
File "hq_main.py", line 28
    main_url = f"https://api-quiz.hype.space/shows/now?type=hq&userId={USER_ID}"
                                                                               ^
SyntaxError: invalid syntax

I think its the f infront of it as i got this error for the logging.fatal command as it had a f infront inside the brackets. Should i remove the f? Im running it off python3 hq_main.py

**Comment by Exaphis** [comment]
Are you using Python 3.6+?

**Comment by zombotesterxyz** [comment]
Ah thanks! and for bearer token and ID its fine if i use a example one that was found in another forum of this repository right?

**Comment by AlexLovesAlpacaa** [comment]
That is fine, you can take any Bearer and User ID, doesnt have to be Yours

**Comment by Exaphis** [comment]
Seems like the problem is solved.
