### ISSUE TITLE
How do you run it?

### ISSUE THREAD

**Issue by AlexRider1** [Exaphis/HackQ-Trivia#86]

**Comment by zombotesterxyz** [comment]
run the following command in the terminal:
python hq_main.py 

Make sure your python version is 3.6 or above.
(For windows its cmd terminal)

**Comment by AlexRider1** [comment]
I did and I recieved a Syntaxerror:invalid syntax

**Comment by AlexRider1** [comment]
Im running 3.6.5

**Comment by AlexRider1** [comment]
![image](https://user-images.githubusercontent.com/37966672/39381973-edd37ac2-4a31-11e8-9c74-b843a01ea311.png)

**Comment by U-r-Unknown** [comment]
U can run by going to 
run ➡run module in code window

**Comment by Exaphis** [comment]
You are running the command in python's console interpreter, not the console. Run ```python hq_main.py``` in the console instead.

**Comment by AlexRider1** [comment]
![image](https://user-images.githubusercontent.com/37966672/39401619-7146d0d0-4b17-11e8-88b5-797a5c4b703a.png)

**Comment by Exaphis** [comment]
Seems like this issue is solved.
