### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by zombotesterxyz** [Exaphis/HackQ-Trivia#88]
You did a great job and its working for me with 80% accuracy.

I was reading the code and have a question about how you got the url of
https://api-quiz.hype.space/shows/now?type=hq&userId={USER_ID}

What did you search that you got that API of HQ Trivia.
It would be great if this modified to work on other trivia games as well.

So i was trying to think of a way to get the API info for other trivia games so how would you go about doing that? Maybe if you have time you can modify it to work on games like The Q, Joyride etc. (Since you are the genius :)

**Comment by Exaphis** [comment]
Yeah, it's possible. The main problem is finding how to connect to the games of other shows and get their questions.
