### ISSUE TITLE
Issue with HQ UK

### ISSUE THREAD

**Issue by mudfins** [Exaphis/HackQ-Trivia#89]
There was an issue today with HQ UK. The questions were pulled successfully, but there were no results.
`Question detected.
Question 12 out of 12
Which of these countries has NEVER been invaded by Great Britain?
['Cuba', 'Vietnam', 'Paraguay']

Searching
['Cuba', 'Vietnam', 'Paraguay']
['countries', 'never', 'invaded', 'great', 'britain']
[]
Running method 1
{'cuba': 0, 'vietnam': 0, 'paraguay': 0}
Running method 2
{'Cuba': {'cuba': 0}, 'Vietnam': {'vietnam': 0}, 'Paraguay': {'paraguay': 0}}
[('Which', 'NNP'), ('of', 'IN'), ('these', 'DT'), ('countries', 'NNS'), ('has', 'VBZ'), ('NEVER', 'RB'), ('been', 'VBN'), ('invaded', 'VBN'), ('by', 'IN'), ('Great', 'NNP'), ('Britain', 'NNP'), ('?', '.')]
Question nouns: ['great britain']
Running method 3
Search processed
URLs fetched

Cuba: {}
Vietnam: {}
Paraguay: {}

Keyword scores: {'Cuba': 0, 'Vietnam': 0, 'Paraguay': 0}
Noun scores: {'Cuba': 0, 'Vietnam': 0, 'Paraguay': 0}

Search took 1.0620067119598389 seconds
Socket closed`

**Comment by U-r-Unknown** [comment]
Does UK version work on Android platform? I tried to download but got the us version

**Comment by mudfins** [comment]
You need a uk phone number i believe

**Comment by perfectusr** [comment]
did you just use a uk user id and bearer token to get the questions to pull? I'm trying to run this as well

**Comment by Exaphis** [comment]
Very weird issue, I will look into it. Is it specific to UK or does this happen on both?
