### ISSUE TITLE
Socket Closed

### ISSUE THREAD

**Issue by ICUI2I** [Exaphis/HackQ-Trivia#90]
Hello,

Awesome job with the bot! Just had a question around the socket randomly closing every x seconds. Below I pasted an example of the socket closing and then getting no output for one of the questions. Is this happening to everybody? Am I doing anything wrong or is there anything I can do to remedy this situation? Or should I just accept that I'm not going to get output for questions here and there (I seem to not get output on ~1 question per game). Thanks for your help!

> Question detected.
> Question 9 out of 12
> The Theridion grallator is a Hawaiian spider famous for what distinctive pattern on its back?
> ['Smiley face', 'Ice cream cone', 'Mickey Mouse ears']
> 
> Searching
> ['Smiley face', 'Ice cream cone', 'Mickey Mouse ears']
> ['theridion', 'grallator', 'hawaiian', 'spider', 'famous', 'distinctive', 'pattern', 'back']
> ['https://en.wikipedia.org/wiki/Theridion_grallator', 'http://eol.org/pages/1188085/details', 'http://alohavalley.com/nananana-makaki%CA%BBi-happy-face-spider/', 'https://www.dogonews.com/2009/05/10/the-happy-spider/page/14', 'https://evolution.berkeley.edu/evolibrary/article/happyface_02']
> Server timeout/error to http://alohavalley.com/nananana-makaki%CA%BBi-happy-face-spider/
> Running method 1
> {'smiley face': 3, 'ice cream cone': 0, 'mickey mouse ears': 0}
> smiley face
> 
> [('The', 'DT'), ('Theridion', 'NNP'), ('grallator', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('Hawaiian', 'JJ'), ('spider', 'NN'), ('famous', 'JJ'), ('for', 'IN'), ('what', 'WP'), ('distinctive', 'JJ'), ('pattern', 'NN'), ('on', 'IN'), ('its', 'PRP$'), ('back', 'NN'), ('?', '.')]
> Question nouns: ['theridion grallator']
> Running method 3
> Search processed
> Server timeout/error to https://www.webstaurantstore.com/guide/678/types-of-ice-cream-cones.html
> URLs fetched
> 
> Smiley face: {'theridion grallator': 0}
> Ice cream cone: {'theridion grallator': 0}
> Mickey Mouse ears: {'theridion grallator': 0}
> 
> 
> Keyword scores: {'Smiley face': 6, 'Ice cream cone': 6, 'Mickey Mouse ears': 1}
> Noun scores: {'Smiley face': 0, 'Ice cream cone': 0, 'Mickey Mouse ears': 0}
> 
> Smiley face
> Search took 5.8341498374938965 seconds
> Socket closed
> 
> Show active, connecting to socket at https://ws-quiz.hype.space/ws/44627
> Connected
> Socket closed
> 
> Show active, connecting to socket at https://ws-quiz.hype.space/ws/44627
> Connected
> Socket closed
> 
> Show active, connecting to socket at https://ws-quiz.hype.space/ws/44627
> Connected
> 
> 
> 
> 
> 
> 
> Question detected.
> Question 11 out of 12
> The only dwarf planet in our solar system's asteroid belt is named for a goddess of what?
> ['Wisdom', 'Agriculture', 'Dawn']
> 
> Searching
> ['Wisdom', 'Agriculture', 'Dawn']
> ['dwarf', 'planet', 'solar', 'system', 'asteroid', 'belt', 'named', 'goddess']
> ['https://solarsystem.nasa.gov/planets/dwarf-planets/ceres/overview', 'https://www.space.com/5861-dwarf-planet-named-hawaiian-goddess.html', 'https://www.space.com/12692-dwarf-planets-solar-system-tour.html', 'https://atlantisrisingmagazine.com/article/ceres-goddess-of-the-asteroid-belt/', 'https://en.wikipedia.org/wiki/Eris_(dwarf_planet)']
> Server timeout/error to https://atlantisrisingmagazine.com/article/ceres-goddess-of-the-asteroid-belt/
> Running method 1
> {'wisdom': 0, 'agriculture': 0, 'dawn': 5}
> dawn
> 
> [('The', 'DT'), ('only', 'JJ'), ('dwarf', 'NN'), ('planet', 'NN'), ('in', 'IN'), ('our', 'PRP$'), ('solar', 'JJ'), ('system', 'NN'), ('asteroid', 'JJ'), ('belt', 'NN'), ('is', 'VBZ'), ('named', 'VBN'), ('for', 'IN'), ('a', 'DT'), ('goddess', 'NN'), ('of', 'IN'), ('what', 'WP'), ('?', '.')]
> Question nouns: ['dwarf planet']
> Running method 3
> Search processed
> URLs fetched
> 
> Wisdom: {'dwarf planet': 0}
> Agriculture: {'dwarf planet': 0}
> Dawn: {'dwarf planet': 0}
> 
> 
> Keyword scores: {'Wisdom': 6, 'Agriculture': 28, 'Dawn': 10}
> Noun scores: {'Wisdom': 0, 'Agriculture': 0, 'Dawn': 0}
> 
> Agriculture
> Search took 6.13198184967041 seconds
> Socket closed
> 
> Show active, connecting to socket at https://ws-quiz.hype.space/ws/44627
> Connected

**Comment by Exaphis** [comment]
Yep, that is a known problem. I don't know what specifically is causing it, but it seems like something wrong with aiohttp's web socket implementation. It is currently in the process of being fixed in the refactor branch.
