### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by RedandYellow** [Exaphis/HackQ-Trivia#91]
I have installed the bot, and all the requirements.

Since there is no game on right now, the bot says 
"Show not on.
Next show time: 2018-04-27 03:00 PM
Prize: $5,000"

but what will the bot say when a game is live?

How exactly does the bot work?

**Comment by Exaphis** [comment]
When the show is live, it will connect to show's socket. As questions come in, they will be automatically detected and the most likely answer will be displayed.
