### ISSUE TITLE
Error when trying to run bot (IndexError)

### ISSUE THREAD

**Issue by gpicon6** [Exaphis/HackQ-Trivia#92]
Traceback (most recent call last):
  File "hq_main.py", line 25, in <module>
    raise e
  File "hq_main.py", line 22, in <module>
    USER_ID = settings[1].split("=")[1]
IndexError: list index out of range

**Comment by Exaphis** [comment]
Have you filled out your conn_settings.txt? If you have, please post the log file here.

**Comment by U-r-Unknown** [comment]
Same error with me. I filled both in settings ( I was just trying to check, the game wasn't on )

**Comment by Exaphis** [comment]
User IDs are being reset. @U-r-Unknown, please post the log file here if you are still having the issue.

**Comment by a314s** [comment]
I am having this exact issue. Here is the log file if it helps. 

CRITICAL:root:Settings read error: ['BEARER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE5MzA3NDE2LCJ1c2VybmFtZSI6ImEzMTRzMTciLCJhdmF0YXJVcmwiOiJodHRwczovL2QyeHUxaGRvbWgzbnJ4LmNsb3VkZnJvbnQubmV0L2RlZmF1bHRfYXZhdGFycy9VbnRpdGxlZC0xXzAwMDFfYmx1ZS5wbmciLCJ0b2tlbiI6InNzUzlSTiIsInJvbGVzIjpbXSwiY2xpZW50IjoiaU9TLzEuMy41IGI4OCIsImd1ZXN0SWQiOm51bGwsInYiOjEsImlhdCI6MTUyNjkzMjA3MCwiZXhwIjoxNTM0NzA4MDcwLCJpc3MiOiJoeXBlcXVpei8xIn0.4s8bTLFk84uCvQ_zJ4ZRyVJfiMkX12zo8tK2zvDpA4E', '', 'USER_ID=19307416']

**Comment by a314s** [comment]
I had this problem but fixed it just now by removing the blank line i had between the Bearer_token and UserID lines.

**Comment by iceeb** [comment]
how tf yall find ur bearer token and userid

**Comment by a314s** [comment]
You need to 
1) get a program to inspect network traffic (I used charles)
2)install the ssl certificate on your phone
2.5)configure your phones http proxy to use your computer ip with port 8888(charles walks you through it)
3Go to your phone settings and make sure you flip it on
4)In charles enable SSL proxing for the HQ api
5) it should be there in plain text.

I can just give you an id but they change them every so often so you will need new ones periodically.

**Comment by a314s** [comment]
The need to figure that out has not arrived yet. But i would imagine you just need to get the new bearer  and ID strings.

**Comment by Exaphis** [comment]
Issue should have been solved in commit https://github.com/Exaphis/HackQ-Trivia/commit/9346ee572c079cdfe9cb3bd022f2fe807b6bd7b2. Let me know if you have any more problems.
