### ISSUE TITLE
Could someone send Bearer token?

### ISSUE THREAD

**Issue by AlexLovesAlpacaa** [Exaphis/HackQ-Trivia#93]
i am having trouble and are so asking if anyone could send me one. Thanks!

**Comment by Jimmychou2** [comment]
lmao spike you're a moron.

**Comment by U-r-Unknown** [comment]
U can use jacobs314's examples here: https://github.com/gjacobs314/HQTrivia

**Comment by AlexLovesAlpacaa** [comment]
What do you mean I’m a moron spike wtf

**Comment by jdleo** [comment]
@AlexLovesAlpacaa Bearer tokens are unique to our accounts. It's how we get authorized in the API. Do research.
