### ISSUE TITLE
Websocket missing questions, disconnecting every 30 seconds

### ISSUE THREAD

**Issue by Exaphis** [Exaphis/HackQ-Trivia#96]

**Comment by savageduckerino** [comment]
It's not a bug. it has to reconnect every 30 seconds because apparently HQ's servers needs a "heartbeat" to stay connected

**Comment by Exaphis** [comment]
Should be fixed in https://github.com/Exaphis/HackQ-Trivia/commit/73a5e82d06dd8dd9534173b49490ab20173d9e3e.
