### ISSUE TITLE
refrator

### ISSUE THREAD

**Issue by tdaddy** [Exaphis/HackQ-Trivia#97]
What is the refactor branch? can't get it running

**Comment by Exaphis** [comment]
It was a branch for just refactoring, but has now morphed into various improvements and bugfixes including the fix for the websocket missing questions bug. The branch currently does not function, it only prints and logs websocket messages. Once the branch is good to go it will merge with master.

**Comment by tdaddy** [comment]
sorry to come back to this, but I noticed some cool improvements in the refactoring branch. was just wondering you had plans to incorporate into the master. thanks @Exaphis

**Comment by Exaphis** [comment]
Yep, will be done soon. Working on some other stuff at the moment.
