### ISSUE TITLE
New Aiohttp version breaks

### ISSUE THREAD

**Issue by OhMyGuus** [Exaphis/HackQ-Trivia#98]
For everyone with issues like "Invalid challenge response" or  "got an unexpected keyword argument 'heartbeat'"
Go back to an older version of aiohttp (for now) by running: 
`pip uninstall aiohttp`
`pip install aiohttp==3.1.1`

**Comment by Exaphis** [comment]
Thanks for sharing your solution, no need for this fix anymore after switching to lomond.
